vercel/swr

README.md

In the `Suspense` example the import method `mutate` is not used. Removing this let the code more clean to read :)

Removing mutate import unused in example README

---

.eslintignore

To prevent `lint:fix` script failing.

ESlint ignore node_modules

---

README.md

Clarify that the passed in fetcher-function must return a promise and is optional

Update `useSWR`-section in readme

---

src/use-swr.ts

Unrelated code from ZEIT's product codebase should be removed (the `shouldShowError` part). Also improved the comments.

Code cleanup and update comments

---

src/use-swr.ts

The problem is caused by `useHydration`. 
When enabling SSR with frameworks like Next.js, we have to match the SSRed result with the client rendered result on hydration, so we skipped from reading the cache.  
But when suspense is enabled, we need to read from cache before the component is mounted.
Close #46 #39

Fix suspense hanging

---

.gitignore
.travis.yml
examples/api-hooks/pages/api/data.js
examples/basic-typescript/pages/api/data.tsx
examples/basic/pages/api/data.js
examples/global-fetcher/pages/api/data.js
package.json
yarn.lock

Like we discussed at https://github.com/zeit/swr/issues/48
I just added pre-commit ( which already catches some Eslint's warnings ).
Also, I added to ignore a folder `.idea` which is generated by Webstorm ( and other Jetbrains IDEs )

Pre-commit, better linting and webstorm support

---

package.json
src/use-swr.ts
yarn.lock

https://github.com/epoberezkin/fast-deep-equal is better than `deep-equal` in both bundle size and performance:
```
fast-deep-equal x 325,485 ops/sec ±0.57% (86 runs sampled)
deep-equal x 73,699 ops/sec ±0.55% (86 runs sampled)
```
From bundlephobia.com:
```
fast-deep-equal: 830B MINIFIED
deep-equal: 7.5kB MINIFIED
```

Use `fast-deep-equal`

---

src/index.ts

This is an odd change, but without this, the IntelliSense doesn't know that `useSWR` is the export from this package (it tries to import from `swr/dist/use-swr` instead),
Functionally, this only adds a new export to the package: `useSWR`

Improve export for IntelliSense

---

package.json
yarn.lock

add @types/lodash.throttle package

add @types/lodash.throttle package

---

package.json
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

cc @pacocoursey as we discussed somewhere else:
Currently if there're multiple SWR hooks sharing the same key, and one of them revalidates, it will broadcast the updated state to others (so we can deduplicate concurrent requests). But it only broadcasts data updates, not errors. This PR fixes the bug.
Also, some tiny performance improvements are made (using `unstable_batchedUpdates` and reducing the number of cache reads), and related tests are added.

Fix error broadcasting

---

examples/api-hooks/README.md
examples/basic-typescript/README.md
examples/basic/README.md
examples/focus-revalidate/README.md
examples/global-fetcher/README.md
examples/optimistic-ui/README.md
examples/pagination/README.md
examples/refetch-interval/README.md
examples/storage-tab-sync/README.md

I think ZEIT team should maintain deployed versions or the CodeSandboxes of each example too.

Add One-Click Deploy button to examples

---

src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

Bug fixes
- fixed #57 and added a test case for it
- fixed #66 and added a test case for it
Also
- introduced cache for errors to support suspense
- changed `noDedupe` to `dedupe` (undocumented API), which is more clear and removes 1 hook inside  (`useCallback`)
- improved code readability

Fix suspense bugs

---

src/use-swr.ts

closes #54 
This is the same "fix" used by the react-redux team - seen in https://github.com/reduxjs/react-redux/blob/2eac86163be2bd5627dab3e33e8b4e0926895442/src/hooks/useSelector.js#L22

replace useLayoutEffect by useIsomorphicLayoutEffect to avoid ssr warnings

---

src/types.ts

Adds `null` to the `keyInterface` type since a key can be null (i.e. when returning from a function doing conditional fetching)
Fixes #94

Add null to types of keyInterface

---

package.json
src/use-swr.ts
yarn.lock

The single packages are deprecated.
Using lodash/throttle will allow bundlers to dedup dependencies.

Use lodash/throttle instead of lodash.throttle

---

src/libs/is-document-visible.ts

`prerender` is deprecated in Document.visibilityState, so it is undefined in `lib.dom.d.ts` 
> @see  https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
The editor will show error in `document.visibilityState === 'prerender'`
So whe can  use `document.visibilityState !== 'hidden'` instead。It's compatible with the deprecated value and passable with editor checking~

Fix visibilityState type

---

examples/pagination/pages/about.js
examples/pagination/pages/page-index.js
src/types.ts
src/use-swr-pages.tsx
test/use-swr-pages.test.tsx

After this change, the SWR -> offset function will pass the entire SWR object (so you can get the error / loading state as well), as well as the index of current page. (`pageSWRs` could be overkill and useless, and it causes some data inconsistency issues.)
```js
swrDataToOffset(data, pageSWRs)
```
e.g.:
```js
useSWRPages(
...,
...,
(data, swrs) => offsetOfNextPage
)
```
```js
SWRToOffset(SWR, index)
```
e.g.:
```js
useSWRPages(
...,
...,
({ data, error, ... }, indexOfCurrentPage) => offsetOfNextPage
)
```
Also added an example for it.

Improve the pagination API

---

src/libs/hash.ts
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

This is a simple and efficient implementation of a frequently requested feature. 
Currently if you want to pass outside args to fetcher (which may change during the lifecycle):
```js
useSWR('key', () => fetcher(...args))
```
It doesn't work, because **the cache is indexed by the key**. Which means if your `args` change, a SWR refetch will not be triggered.
GraphQL:
```js
const personQuery = `
query Person(id: ID, name: String) {
person(id: $id, name: $name) {
id
}
}
`
// Reuse same query with different variables.
request(personQuery, { variables: { id: 42 } })
request(personQuery, { variables: { name: "Alice" } })
```
Multiple params:
```js
const token = useToken()
// SWR will still read the stale data even if `token` changes
const { data } = useSWR('/api/user', url => fetchAPI(url, …
```

Args as key

---

README.md
src/types.ts
src/use-swr-pages.tsx
src/use-swr.ts
test/use-swr.test.tsx

Can partially help in resolving the issue: #11 in the interim 
(worded weirdly to avoid a auto-close)

Adding initialData

---

README.md

Clarify that swr does not implement HTTP RFC 5861, but implements a cache invalidation strategy popularized by HTML RFC 5861, which may make reader confusing.

Clarify about HTTP RFC 5861

---

src/use-swr.ts

We are using SWR in an environment without `window` variable, so need to check for the `window` variable.

Check for window before using it

---

README.md
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

With this change, the `data` parameter of `mutate` can be a promise, which returns the data or throws an error:
```js
mutate(key, Promise<Data>)
```
It can simplify scenarios like
```js
const newData = await update(...)   // some POST APIs return the updated data
mutate('/api/data', newData, false) // disable the revalidation here
```
to:
```js
mutate('/api/data', update(...)) // POST + mutate w/o revalidation
```
Related: #93.

Add async mutation support

---

package.json

fix #137 
- Add `react-native` to `package.json` to point to `esm` entry point
- Metro bundler will pick up the entry point per https://github.com/facebook/metro/blob/501add8cc1c2674ddb98302e47ff5194a80de3d7/packages/metro/src/ModuleGraph/node-haste/Package.js#L107-L130
**Test Steps**
- Clone `https://github.com/n3tr/ReactNativeSWRExample` (pointing to my custom build `swr` with `react-native` entry point inside `package.json`)
- `yarn install`
- `yarn start`
- Open new terminal window and run `yarn ios`
- App should build successfully

Add react-native entry point to package.json

---

README.md
tsconfig.json

This pull request:
1. fixes incorrect value provided to `tsconfig.json`'s `lib` property (`DOM` -> `dom`)
2. fixes small typos on `README.md`

Fix tsconfig's "lib" property, along with small improvements to README.md

---

README.md
src/libs/hash.ts
src/use-swr.ts

- fix the case that the args array is empty:
`useSWR([])` shouldn't fetch
- fix hashing primitive types:
`useSWR([null])` ≠ `useSWR(["null"])`
- add a [Prefetching Data](https://github.com/zeit/swr/tree/bug-fixes#prefetching-data) section to the readme
- fix #144 and remove `useHydration`, cause we don't have to worry about mismatching for now (currently there's no persistent cache like local storage or indexedDB. So in both SSR, Suspense and normal prerender + CSR, the hydration result will always match the rendered template).

Improvements

---

examples/axios-typescript/libs/useRequest.ts
package.json

This replaces the `'` in `package.json` scripts with `"` so that they can also run on Windows.
It also removes an unused import in an example I added in a previous PR.

Scripts on windows

---

src/types.ts
src/use-swr.ts

Make sure `mutate`, `revalidate` and `trigger` won't be ignored because of deduping and race conditions:
```
+------------------------------------------------------->A
ongoing request                                         stale response
+-------------------------------------->B
revalidate                             latest data
```
It should show **B** but the result is overridden by **A**, which is wrong. The sequence of responses should be ordered increasingly, by the start time of the corresponding requests.
Fix #153.

Fix race condition

---

package.json

This PR opens up the peer dependency requirement to allow for newer minor releases of React without SWR starting to complain.

Allow newer minor versions of React as peer dependency

---

src/use-swr.ts
test/use-swr.test.tsx

If user wants to call `useSWR` hook with config object as second parameter, provided config object is interpreted as fetcher function and hook won't work.
This PR fixes that bug and adds test.

Fix config as second parameter in use-swr

---

test/use-swr.test.tsx

close #177
ref #173
original #153

test: add race condition test

---

README.md

We shouldn't recommend `useMemo(() => ({ id }), [id])`. It's not elegant, and the cache is not-reusable.
For example `id` changes from 1 → 2 → 1, and the cache can not be reused since `A !== C`:
```js
const A = useMemo(() => ({ id: 1 }), [1])
const B = useMemo(() => ({ id: 2 }), [2])
const C = useMemo(() => ({ id: 1 }), [1])
```

Improve multiple argument example in README

---

README.md
src/config.ts
src/types.ts
src/use-swr.ts

I love `useSwr`! I’m using it to build a [London Underground status site](http://underground.lucid.toys/).
While testing the app on slow/no network speeds, I noticed that `useSwr` will continue polling endpoints even if the navigator is offline. This PR adds an additional boolean check in the `tick` function to ensure that requests aren’t sent if the browser is offline.

Prevent polling when browser is offline

---

src/use-swr.ts
test/use-swr.test.tsx

This fixes #194.
I wasn't sure if this should be set via another option or not but if so let me know and I can update.

skip immediate revalidation when initalData is provided

---

src/use-swr-pages.tsx
src/use-swr.ts
test/use-swr.test.tsx

By moving _data, error, isValidating_ away from the state (`useReducer`) to a ref (`stateRef`), the hook won't trigger another re-render anymore when one of these values updates. 
Instead, we add getters to these values (implemented with `defineProperties`). Once a value is read, it will be marked as a dependency immediately. Thus, we can trigger a re-render if any dependency changes in the future.
With this change, `useSWR` will never cause unnecessary re-renders:
```js
const { data } = useSWR(...)
// will not re-render if `isValidating` or `error` changes
```
No changes needed from the user side (and Suspense mode is not affected).
Fixes #184. Related #144, #114.
Published at ~~`swr@0.1.13-beta.0`~~ `swr@0.1.15-beta.0`.
---
This PR has been running on our production for a couple of …

Reduce re-renders by auto detecting state dependencies

---

src/use-swr.ts

React Native app crashes after `swr` update because `revalidateOnReconnect` option is `true` by default and React Native has no `addEventListener ` and `removeEventListener ` in global scope.

Check if addEventListener and removeEventListener exists

---

src/config.ts

I was reading the source to see how it works and I found this configuration block that had way too many ifs for my taste and that it could be made smaller.
As lightweight is one of the goals of this library. I think a small win is still a win :)
This shaves 44B off the commonjs version of the library, (should be similar in ESM after minification)

Reorganize slow connection code. Make it a tiny bit smaller

---

src/use-swr.ts

I noticed that React Native still crashes after applying the changes from #217.
More specifically the error I see is:
```
ReferenceError: Can't find variable: addEventListener
```
If you are seeing the same issue, this PR fixes that by checking if the variable `addEventListener` is defined as suggested here: https://stackoverflow.com/a/519157/2310187

Fix check for addEventListener existence

---

src/use-swr-pages.tsx

Currently, changing the pageKey doesn't reset the pages cache, and theres no other way to clear the pages cache.
Might solve #189

Moving page cache to use a cache map

---

src/use-swr.ts
test/use-swr.test.tsx

`await CONCURRENT_PROMISES[key]` should be called *before* deduping. Because there could be this potential bug, say `dedupingInterval` is 2s:
```
0s: A ... GET /api
2s: delete CONCURRENT_PROMISES[key]
3s: B ... GET /api
4s: B -> response
5s: A -> response
```
Which is a race condition, the request fired first got returned last.
(Also added a test for `mutate` in this PR)

Fix a race condition bug

---

src/use-swr.ts
test/use-swr.test.tsx

fix: disable dedupe when trigger/mutate (#271)

---

README.md
src/config.ts
src/types.ts
test/use-swr.test.tsx

Add errorRetryCount config option to limit error retries.
closes #276

add errorRetryCount config option

---

examples/axios-typescript/libs/useRequest.ts

Fixed potential typescript error in `examples/axios-typescript`

---

.eslintignore
src/cache.ts
src/config.ts
src/index.ts
src/types.ts
src/use-swr-pages.tsx
src/use-swr.ts
test/use-swr.test.tsx

This attempts to partially resolve #212 and resolves #161 and resolves #237 and resolves #158
I updated this to only expose the global cache, I kept the cache interface, adding a way to tell the `set`, `delete` and `clear` methods if you want to notify components reading from the cache, this way `mutate` can call `cache.set` and `cache.set` can also call `mutate` as a notification method without running on a infinite loop (mutate calls `cache.set` with this flag as `false`).
I did this to come back to custom cache once I found a way to let `mutate` know which cache to call without manually passing it.
~I created a CacheInterface and make the global config create a default instance of the cache, also exported both the interface and the Cache class.~
~I also updated `useSWR` to read from …

Expose Cache

---

src/use-swr.ts

Should only continue polling if `refreshWhenOffline` is set to true (allowed to poll offline), or it's online.
Close #247. Thanks @madmanwithabike for reporting!

Fix polling conditions

---

examples/axios/libs/useRequest.js

Looks like `revalidate` has been changed to `mutate`, so if you try to use this example it'll say that `mutate` is not a function.

Change useRequest.js to use `mutate`

---

src/use-swr.ts

```js
reconnect = addEventListener('online', softRevalidate)
```
`addEventListener()` return `undefined`，should change to:
```js
addEventListener('online', reconnect = softRevalidate)
```

Fix 'reconnect' assignment

---

src/use-swr.ts
test/use-swr.test.tsx

Fix #295.
Additionally, test case `dynamic-13` seems to be the same with `dynamic-12` so I just changed it.

Dedupe duplicate requests after mutation

---

README.md
examples/server-render/README.md
examples/server-render/package.json
examples/server-render/pages/[pokemon].js
examples/server-render/pages/index.js

Next.js 9.3 introduced a new API `getServerSideProps`.
https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support

Update examples/server-render: Use getServerSideProps

---

src/use-swr-pages.tsx

Fix for #290 "Warning in React 16.13.0"
[New warnings in React 16.13](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render) — especially triggering `setState()` from another component.
This change:
* Is minimal. It wraps `setTimeout()` around two `setState()` calls in `useSWRPages()`. There's a comment in it that we can probably delete.
* Silences the new warnings people are seeing in #290 — tested on branch [@neolefty/publish](https://github.com/neolefty/swr/tree/publish) and available to try out from [@neolefty/swr](https://www.npmjs.com/package/@neolefty/swr).
* Probably adds another rendering roundtrip by delaying `setState()`. But that's actually the point of the new warnings, I think.

Wrap side effects to fix new warnings in React 16.13

---

src/use-swr.ts
test/use-swr.test.tsx

Inside `revalidate`, `keyRef` will be overridden by the request key when one request finishes. Consider 2 requests initialized by 2 different keys `key1` and `key2` (key has changed after the 1st request fired), if the 1st took longer, `keyRef` will be changed to `key1` eventually.
In a new read access to the getter, `undefined` will be returned since the keys no longer match.
Run the first `should respect requests after key has changed` test without this fix.
`keyRef` check is not necessary at all, let's just remove it. Inside `useEffect` https://github.com/zeit/swr/blob/master/src/use-swr.ts#L376-L382, every time `key` updates, we will get the latest data from the cache and dispatch the state synchronously. 
```js
const currentHookData = stateRef.current.data
const latestKeyedData = …
```

Fix a race condition bug and remove keyRef check

---

src/types.ts
src/use-swr-pages.tsx

I noticed `pageSWRs` in the `pagesResponseInterface` type was typed with `<any, any>`. I fixed this with the `Data` and `Error` generics.

Add `Data` and `Error` generics to `pagesResponseInterface`

---

examples/local-state-sharing/package.json

```
[ error ] ./pages/index.js 
Module not found: Can't resolve 'swr' in '/Users/s07840/swr/examples/local-state-sharing/pages'
```

use latest swr in examples/local-state-sharing

---

test/use-swr.test.tsx

make sure polling stop when refreshInterval is 0

test: imporve dynamic polling interval test

---

src/use-swr.ts

In concurrent mode Suspense is supported in server side, we can remove this warning.

Remove the server side suspense warning

---

src/types.ts

When using `mutate` with a function ([as per the README example](https://github.com/zeit/swr#mutate-based-on-current-data)), I had a TS error coming from an invalid type.
That's because the callback is an async function returning a promise which needs to be resolved ([and is in the code](https://github.com/zeit/swr/blob/48e199e3ccf3addeee1bf3e25aad4711647dd355/src/use-swr.ts#L87)). I fixed the type in this PR.
Code:
```ts
mutate('/api/users', async (users) => {
const user = await fetcher('/api/users/1')
return [user, ...users.slice(1)]
})
```
TS error:
```
Type 'Promise<User[]>' is missing the following properties from type 'User[]': length, pop, push, concat, and 26 more.
Did you mean to call this expression?
```

Fix return type of mutateCallback

---

src/use-swr.ts
test/use-swr.test.tsx

bugfix for #361 
I feel the issue was introduced in e6cca41846241e3c29b98cb4b8eba0e7ccc94 
`revalidate` gets excuted when react clearing effects, which is after the key changed.
see the example provided in #361 , when the key and data are both updated to the next state (since fetcher is synchornized and finished immediantely), swr still use the data of last key instead of retriving from cache with new key.
1. user triggers setState -> key change -> data change (sync)
2. swr detects key change
3. swr returns memoized state with last data **(not expected)**
4. swr `revalidate`
5. swr returns correct value

fix: data inconsist on key change when fetcher is synchronized

---

README.md
src/config.ts
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

Hi there,
we're currently using useSWR but we have found conditional revalidation a bit limiting.
For example we have some occurences where we want to trigger revalidation only after a certain action is being taken (could be a button click).
With current conditional revalidation techniques we are forced to use an additional state just to prevent first validation on mount.
This PR aims to add a simple autoLoad (or whatever other name) flag in the options so that automatic revalidation on mount can be prevented and we can simply trigger it directly in a callback (for example a button onClick).
Best,
Gabriele

revalidateOnMount flag that disable automatic revalidation on mount

---

README.md

Replaced the outdated `assets.zeit.co` hostname with `assets.vercel.com`.

Updated asset link

---

src/types.ts

I use swr mutate in a typescript project in combination with a [curried produce](https://immerjs.github.io/immer/docs/curried-produce) from immer, which returns a function that accepts the current data and returns the new data. With version 0.2.1, my build breaks because of a changed type in mutateCallback. This is only a typescript error - the code continues to work.
In #381, the return type for mutateCallback was changed to a promise. In order to also support this curried produce from immer, it should also accept the non promise value.
You can see the error in action here: https://codesandbox.io/s/elated-gould-j4pfc

Change mutateCallback type to allow non-promise return value

---

examples/axios-typescript/libs/useRequest.ts

useRequest hook does not return bound mutate function which is returned by useSwr hook.
so it becomes impossible to use bound mutate. This pr fixes that issue by returning mutate.

Fix No bound mutate returned by useRequest hook.

---

package.json

output es5 synatx (configured in tsconfig.json) for both esm and cjs build

build: use es5 syntax for esm build (#443)

---

README.md

This doesn't appear to be well documented. (See #426.)

Update docs to explain dependent fetching with falsy

---

src/use-swr.ts
test/use-swr.test.tsx

Took me a while to figure out how the testing works. I hope the test is okay for this now. I locally tried it with `revalidateOnMount: true` as well, so `fetcher` gets called and will change the data to `SWR` later, but I was unsure if that extra test isn't already done through the revalidation tests.

Use initialData in suspense mode if provided

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

* create issue template for bug reporting
* add external link to swr discussion board

docs: setup issue template

---

src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

Right now `mutate` is typed to return a Promise with the updated value, but if you don't pass a second argument `mutate` calls `trigger` that was not retuning anything.
This PR changes `trigger` to return a promise always, if it didn't received a key it's an immediately resolved promise, if it has key and there are updaters for that key, it uses Promise.all to await for all of them to be resolved and then returns the new cached value, lastly If there are no updated it will return an immediately resolved promise with the current cached value.
This should allow us to do:
```ts
import { mutate } from 'swr'
// do something
await mutate(key)
// do more things after the cache key was revalidated
```
This fix https://github.com/zeit/swr/issues/355

Make trigger return a promise resolved to the new cache value

---

package.json

This PR focuses on changing the value of the `repository` property to `vercel/swr`. This renaming is also being applied for the `dev` command found in scripts.

Change name to ▲Vercel

---

src/use-swr.ts
test/use-swr.test.tsx

test: add test case for error updating in cache when mutate

---

src/cache.ts
src/types.ts
src/use-swr-infinite.ts
src/use-swr.ts
test/use-swr.test.tsx

* try to make cache pure. currently swr had 2 standalone paths to trigger revalidation of data: one is `mutate(key, value, true)` another is `cache.set(key, value, true)`. the way cache to revalidate data is leveraging mutate api, which means `mutate` is the out path to trigger revalidation.
* this can also resolve circular dependency issue of swr itself (mentioned in https://github.com/vercel/swr/pull/487#issuecomment-650562001). now we had clear deps path like the following:

enhance: remove mutate calls from cache

---

package.json
src/use-swr-infinite.ts
test/use-swr-infinite.test.tsx

Page size should only be reset on **re-render** (not first render). That ensures scroll position restoration to work correctly.

Fix page size persistence when remounting

---

src/config.ts
test/use-swr.test.tsx

thanks @whj1995 for spotting out the bug. This should handle the edge case where user decides to set errorRetryCount to 0 instead of using the shouldRetryOnError boolean flag.

don't retry on error if errorRetryCount is set to 0

---

src/use-swr.ts

Resolve #494 
react exp version will warn setState calls when component is not mounted. on suspense mode, swr trigger revalidate and lead to call `rerender` when the component is not mounted yet.

fix: check if mounted when trigger rerender

---

src/index.ts
src/use-swr-infinite.ts

Rationale: Extending these interfaces in a TypeScript project when composing your own hooks using SWR.
You can already do this with config/response interfaces used by `useSWR` as these are already exposed.

Export interfaces used by useSWRInfinite

---

src/use-swr.ts
test/use-swr.test.tsx

Fix #556
mutate failure should throw the error out. error is hidden when use `mutate` and `useSWR` hook at the same time.
* in `mutate`: throw error after onUpdate callback executed
* update test: add try catch on top of `mutate` call when it might throw

fix: should throw when mutate failed

---

src/use-swr.ts
test/use-swr.test.tsx

leverage the existing simple fallback code from https://github.com/vercel/swr/pull/446/files

enhance: fallback to setTimeout when request idle callback is not available

---

examples/focus-revalidate/pages/api/user.js
src/config.ts
src/use-swr.ts

Resolves #474 , attach online event listeners in config 
* build swr locally and yarn link to the examples/focus-revalidate 
* add one more swr hook there
* disconnect and reconnect the network in devtools
* expected: the requests get re-fetched

enhance: move online listeners to config (#474)

---

package.json
src/use-swr.ts

close #574 
With this PR, it will look like this in the React DevTools:
I'm not sure if we need to show `undefined` when the data is not returned as expected? like this:

Add useDebugValue to show the data label in the React DevTools

---

src/use-swr.ts

we can use ?? operator of typescript 3.8 in future
this will fix bug of infinite loading when using suspense and a fetcher which resolved a falsy value
close issue #517

fix problem of unnecessary revalidates when resolved data is falsy

---

src/use-swr.ts
test/use-swr.test.tsx

Resolve: #508 #515 
Now the `eventsRef` read the config via the `ref`,which always capture the lastest version of the config callbacks.
This fix the problem of the stale closure related to the config callbacks.

fix: `eventsRef` should trigger the lastest version of config callbacks

---

src/use-swr-infinite.ts

First of all, thanks for this awesome library!
This PR makes usage of `size` and `setSize` easier with Typescript by making them not undefined. From what I see these variables are always defined
```ts
const { setSize, size } = useSWRInfinite(...)
const loadMore = () =>
// Typescript error: Cannot invoke an object which is possibly 'undefined'
setSize(
// Typescript error: Object is possibly 'undefined'.
size + 1
) 
```

Fix useSWRInfinite response type

---

src/use-swr.ts

This is so that you do not get an unnecessary rerender when the key has changed but the cached data is the same. In my case I'm conditionally fetching and when the key becomes valid I get an extra render while data is still `undefined`.
A few changes are from a linter that I assume ran on commit? Let me know if it's uncouth to have left them there.

Do not rerender if key changes but not data

---

src/use-swr.ts

when dispatch, just add a compare with current state to prevent unnecessary rerender

chore: optimization dispatch

---

src/libs/hash.ts
test/use-swr.test.tsx

This is a proposed fix for the issue I raised in https://github.com/vercel/swr/issues/611 .
See the original issue for more details on the issue I'm facing.

add function key arguments to WeakMap so they trigger revalidation on identity change

---

src/use-swr.ts
test/use-swr.test.tsx

Fix #632 
- The old implementation of pooling can't stop timer if refreshInterval changes **during revalidate**. This problem can be solved by using the configRef to get the latest refreshInterval.
- The old implementation of pooling will stop the old timer if refreshInterval changes. ~~But the new implementation of pooling ***will not clear the old timer***~~.

try fix cannot stop polling by setting refreshInterval (#632)

---

.gitignore
src/cache.ts
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

This fixes https://github.com/vercel/swr/issues/549 by caching and broadcasting `isValidating` in the same way that `data` and `error` are cached and broadcasted.
**Before**
**After**

Promote isValidating to the global level of data and error

---

README.md
package.json
src/config.ts
yarn.lock

Discussion: https://github.com/vercel/swr/discussions/645
> TLDR: `dequal` (especially `dequal/lite`) is smaller and faster. Feature support is identical between FDE and "lite" mode
There are some extra changes in the diff from the pre-commit hook.
FDE is still a part of the lock file through `eslint->ajv` (dev deps).
Build still successful and tests pass locally.

chore: use `dequal/lite` for default comparisons

---

src/libs/hash.ts
src/use-swr-infinite.ts
src/use-swr.ts
test/use-swr-infinite.test.tsx
test/use-swr.test.tsx

The bound `mutate`/`setSize` from `useSWR` and `useSWRInfinite` should not change over re-renders, so you can include them safely inside hook dependencies (or not include them). It should work just like a `setState` in React.
This PR removes the `key` dependency from `boundMutate` in `useSWR`, instead we use the ref of the key.
We used to do this in `useSWRInfinite`:
```js
const swrInfinite = swr
//...
const mutate = swrInfinite.mutate
swrInfinite.mutate = useCallback(..., [mutate])
```
So after one pass, the original object's field `swr.mutate` will be updated to `useCallback(...)`. So upon the next renders, the dependency `[mutate]` will always be considered changed.
Closes #664

Remove unnecessary dependencies from `mutate` and `setSize`

---

examples/local-state-sharing/README.md
examples/suspense/README.md

This PR adds README files to examples/suspense and examples/local-state-sharing.
I referred to the readme of other examples.
Please check the section "The Idea behind the Example".

Add README to examples

---

src/types.ts

This allows again for lazy execution since passing `undefined` broke with the introduction of a default fetcher in #367

Allow passing null as the fetcher function for lazy execution

---

src/config.ts
src/libs/web-preset.ts
src/types.ts
src/use-swr.ts

provide a way to let other js runtime like RN to customize the way of listening events. then the focus/visible/connect are able to be associated with platform behaviors
set the listener attaching process to config
add `config.setOnFocus(callback)`
add `config.setOnConnect(callback)`
for web browser, the fallback will be like following, for RN, it could be sth else
```js
setOnConnect(callback) {
window && window.addEventListener && window.addEventListener('online', callback, false)
}
```
then `config.setOnConnect` becomes a call that can register event listeners, the event listeners are actually executing the revalidators. i.e.
```
// reconnect revalidate
if (preset.setOnConnect) {
preset.setOnConnect(() => revalidate(RECONNECT_REVALIDATORS))
}
```
in the setup process, we attach the …

feat: customizable listener

---

.travis.yml
package.json
src/use-swr.ts
test/use-swr.test.tsx

1. add `npm build` to the Travis test command
2. mark the package as side effects free for better tree shaking (check "Exports Analysis" in: https://bundlephobia.com/result?p=swr@0.3.8-beta.2)
3. deprecate the global `trigger`

Code optimize

---

src/use-swr.ts
test/use-swr.test.tsx

We have this inconsistency issue in current version:
```js
// we call `mutate` twice, synchronously, with a callback that reads the latest value
// let's assume the initial data is `0`
mutate('key', v => v + 1, false)
mutate('key', v => v + 1, false)
```
The data should be `2` after these 2 synchronous mutation calls. However if you test, it is actually `1` (here's a great [bug reproduction](https://codesandbox.io/s/swr-mutate-race-condition-gnrs3) from @derindutz).
The cause is that we are always updating the cache in async (as #619 tries to fix), so the argument `v` passed to the second mutation callback is still `0`. To make it clear, here's a diagram addressing this bug:
We at first [tried](https://github.com/vercel/swr/pull/619/files#diff-755ef1ecc6f2f4c1cc601c6091dfcba5f674c653863b70 …

Fix race condition when calling mutate synchronously

---

src/use-swr.ts

when use SSR with swr  in Deno i got a warning:
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```jsx
import useSWR from "https://esm.sh/swr"
export default function Home() {
const { data } = useSWR('/api/hi', fetcher);
if (!data) {
return <div>loading...</div>
}
return <div>hello {data.name}!</div>
}
```

refactor: support SSR in Deno

---

src/types.ts
test/use-swr.test.tsx

~1. `Promise<Data | undefined>` because `mutate` implementation handles `undefined` values.~
`mutate` implementation can  pass `undefined` values to the `mutateCallback`: https://github.com/vercel/swr/blob/9e734aaff7d3082fc9fd7945f615fb63621b2bc7/src/use-swr.ts#L138-L144

Fix `mutateCallback` types

---

src/use-swr.ts

close #773
When I started reading `use-swr.ts`, it was hard to imagine what arguments dispatch was receiving at first. I think it will be somewhat more readable.
Also, after `yarn run lint:fix`, a line break occurred around line 30.

dispatch's payload type is actionType and run lint

---

src/use-swr.ts

Fix suspense

---

src/use-swr.ts
test/use-swr.test.tsx

Fix #199 
~~* tear down work when key turns to empty, unmount state should be false if it's mounted before.~~
~~* dispatch `isValidating` as `false`~~
scenario: key: v1 -> v2 -> ''
~~in this case, when transfer to empty key the unmountedRef will be set to `true`, which lead dispatch take no effect. so I set it to true if it's not really unmounted.~~
~~then dispatch `isValidating` to `false` to ignore the ongoing requests.~~
~~update `keyRef` to match key, then isValidating getter will retrive states from `stateRef`~~
forcedly return false when key is falsy

fix: mark isValidating as false when key is falsy

---

src/use-swr.ts

config callback may also cause ```Can't perform a React state update on a component that hasn't mounted yet```
[Repo](https://codesandbox.io/s/long-sun-me0tz?file=/src/App.tsx)

fix: do mount check in config callback

---

src/libs/hash.ts

If args[i] is null, always return `@null`.
Now, check `typeof args[i] === 'string'` and run `String(args[i])`. This is unnecessary.
This fix should improve readability and speed by a small amount.

Return '@null' if args is null ASAP

---

src/use-swr.ts
test/use-swr.test.tsx

For case:
req1 -----> res1
req2 ---------------->res2
The `isValidating` was false over the period of res1 and res2, and should be true.
This PR try to fix it.
See test case for detail

Keep isValidating be true when there are two concurrent requests

---

src/config.ts
src/types.ts
src/use-swr.ts
test/use-swr.test.tsx

give user ability to decide whether they want revalidation in some edge cases:
* page transition on slow connection that revalidations can cause more errors
* page is in background sometimes they don't want any revalidation
* add `config.isPaused()`
* stop doing revalidation on `config.isPaused()` is `true`
related discussion [841](https://github.com/vercel/swr/discussions/841)

feature: provide config.isIdle indicating idle state and stop revalidation

---

src/use-swr.ts

Fix #852
https://github.com/vercel/swr/blob/00c5847ce6e95902920933aa1d49c7143f8ce4ba/src/use-swr.ts#L687-L697
when timer is been cancelled, but to the timer procedure, it cannot know if the last timer is cancelled. so it started a new timer again.
steps:
start timer > revalidate > timer is cancelled due to effects > but still start a new timer (with legacy `revalidate`).
mark timer as null when cancel it and the cancel state is kept as condition. then swr can avoid to start a new timer again.

fix: clear refresh timer on effects change and check it on starting new timer

---

src/use-swr-infinite.ts
test/use-swr-infinite.test.tsx

Currently `useSWRInfinite` always refetches the first page because of this line:
```js
(typeof force === 'undefined' && i === 0)
```
and it will not reuse the cache from `useSWR`. This PR fixes that so if there is no `originalData` (the first render), but has `pageData` (has cache), we directly return the cache.

First page of useSWRInfinite should reuse the cache from useSWR

---

src/use-swr.ts
test/use-swr.test.tsx

`config.isPaused()` works with global variable states, but when you switch to react states, need to use ref of config

enhance: let config.isPaused works with react state

---

src/libs/web-preset.ts

related to #522 
`navigator.isOnline` might be directly accessed in some corner cases leading to crashes. 
known runtime: 
* node.js with next.ks
* ink

fix: add protection for navigator

---

.github/workflows/test.yml

This PR adds GitHub Action for typecheck, test, and lint tasks.
ref. https://github.com/vercel/swr/pull/872#issuecomment-756849888
The setup is based on the configuration of TravisCI.
https://github.com/vercel/swr/blob/master/.travis.yml
The result of a GitHub Action is here.
https://github.com/koba04/swr/runs/1673115189?check_suite_focus=true
If you have any requests like running on various environments (Node versions and OS), I'll add them to the configuration.
I have also left the setting for TravisCI, so let me know if you no longer need the setting, then I'll remove it.

ci: add GitHub Actions for CI

---

.travis.yml

I've added a GitHub Action to replace with Travis CI at #879.
The GitHub Action seems to work fine. So I've created a PR to remove Travis CI from this repository.
https://github.com/vercel/swr/actions
It would be nice if this PR is merged after a while.

ci: remove Travis CI

---

README.md

Ran into issues with this when using SWR for local state sharing. It seems that the default value for the fetcher is actually `window.fetch` and not `undefined`:
https://github.com/vercel/swr/blob/master/src/config.ts#L71

 Update default fetcher documentation in README.md

---

src/use-swr.ts

I found that revalidateOnFocus is not working on iOS 13. 
To fix, `window.addEventListener('visibilityevent', callback)` should be replaced by `document.addEventListener('visibilityevent', callback)`
Ref: https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event

fix: revalidateOnFocus not working on '< iOS 14' 

---

src/use-swr-infinite.ts

This PR fixes #780. I've left a comment on the intention.

refactor: use getter functions to avoid unnecessary re-renders

---

src/use-swr.ts

Update from 0.2.3 to 0.3.0 would cause issues when running my Jest tests, it would report an undefined function. After some research, the function in question is `rAF` which is set to `null` in server environments. 
Looking at the diff between 0.2.3 and 0.3.0 (https://github.com/vercel/swr/compare/0.2.3...0.3.0) there used to be a check for `IS_SERVER` but it was removed (`rAF` is named as `rIC` still in the diff).
Since im not that familiar with the project i'm not sure if this is meant to be like this or if adding back the `IS_SERVER` is okay, but i wanted to approach the issue via a PR rather than an issue.

fix: add server check back before calling rAF

---

src/use-swr-infinite.ts
src/use-swr.ts

This is based on #263 and  I've fixed some warnings of `react-hooks/exhaustive-deps`, which can be safely fixed. 
- `renderer` is a setState function that `useState` returns, which is guaranteed to be stable. But the eslint plugin cannot recognize that `const rerender = useState<boolean>(false)[1]` is the setState function, so I've changed the statement.
- https://reactjs.org/docs/hooks-reference.html#usestate
- The `dispatch` function uses `config.suspense`, but it's not in the deps array, so I've added it to the deps array.
This PR doesn't fix all warnings because some of them seem to be valid and adding missing deps variables might cause issues, so we have to fix the issues carefully and consider adding missing deps variables or `eslint-disable` comments. I'll work on that after this …

fix: react-hooks/exhaustive-deps warnings

---

test/use-swr-infinite.test.tsx

This PR adds a test for `useSWRInfinite` with `initialData`.
I've added the test, but I'm still not sure of the expected behavior in the case.
How should `useSWRInfinite` behave combined with `initialData`?
- Does `useSWRInfinite` support `initialData`?
- The `initialData` option is not mentioned in [the document](https://swr.vercel.app/docs/pagination#parameters), but [a related issue](https://github.com/vercel/swr/issues/588) is being tagged as `bug`.
- If `useSWRInfinite` supports `initialData`, how should the `initialData` be handled?
- Is the `initialData` stored in the cache store? Currently, it seems not to be stored in the cache. If so, I'll fix the issue.
- https://github.com/vercel/swr/compare/master...koba04:add-test-for-swrInfinite-with-initial-data?expand=1#diff-e7360ba75395f5 …

test: add a test for useSWRInfinite with initialData

---

test/use-swr-infinite.test.tsx
test/use-swr-int.test.tsx
test/use-swr-local-mutation.test.tsx
test/use-swr.test.tsx

This is a PR to follow up #886 and fixes all `react-hooks/exhaustive-deps` warnings in tests.
They can safely be ignored in these cases.
As I mentioned on https://github.com/vercel/swr/pull/901#issuecomment-760216332, there are duplicated tests and I've fixed each warning twice.
I'll remove the tests if there is no reason for the duplication.

refactor: fix all react-hooks/exhaustive-deps warnings in tests

---

README.md

fixes #353 
I've replaced a Graph.Cool endpoint with a fake GraphQL endpoint.

docs: use a fake GraphQL endpoint instead of graph.cool

---

src/use-swr-infinite.ts

This is a PR to follow up #902 and #886, and fixes all react-hooks/exhaustive-deps warnings in `useSWRInfinite`.
I've disabled the warnings by `eslint-disable-next-line` comments and removed `swr.mutate` because it's an immutable reference.
https://github.com/vercel/swr/blob/81824c7df8666817075d386854711bfc153cc99a/src/use-swr.ts#L348-L353

refactor: fix all react-hooks/exhaustive-deps warnings in useSWRInfinite

---

src/use-swr-infinite.ts
test/use-swr-infinite.test.tsx

This PR fixes a `useSWRInfinite` bug introduced in #799 by me (thanks @pacocoursey for reporting). To reproduce, just simply use `refreshInterval` with `useSWRInfinite`, and the first page will never be revalidated:
Reproduction: https://codesandbox.io/s/swr-infinite-forked-mi7rf?file=/src/App.js
The cause of the bug is this LOC: 
```js
(typeof force === 'undefined' && i === 0 && originalData) ||
```
...to determine if we should fetch this page or not, which can break down into:
- `typeof force === 'undefined`: It's not a force revalidation, like `mutate()`.
- `i === 0`: It's the first page, we don't want to revalidate every page upon focus.
- `originalData`: It's not the first render. **This is the mistake**.
What we want to achieve for `useSWRInfinite` is this experience: If we have the …

Fix the revalidation condition of the first page

---

jest.config.js
package.json
yarn.lock

Currently, `screen` isn't recognized because `@types/testing-library__react` doesn't have the type definition.
`jest` doesn't raise the error because `diagnostics` of `ts-jest` is disabled.
This can be fixed by updating `@testing-library/react` to v10 and I've enabled the `diagnostics` again.
But it causes another problem caused by a breaking change of `@testing-library/dom` v7.
> MutationObserver shim removed.
https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0
To fix this, I've updated `jest` packages to v25, which includes MutationObserver.
Unfortunatelly, some tests in `use-swr-test.tsx` are still failed. I can fix these tests, but they have already been fixed in separated files at #901.
I assume this PR would pass CI after #881 and #896 have been merged and …

test: recognize type definition for screen of testing-library/react

---

src/types.ts

**UPDATED** This PR adds a comment to describe why `fetchFn` accepts `null`.
-----
This PR removes `null` from the type definition for `fetchFn`, but please correct me if I'm wrong.
I couldn't find any documentation about the behavior for passing null as a `fetcher` function. A case with `undefined` is documented though.
I also couldn't find any implementation for the case.
Is SWR supporting the case? If so, what is the expected behavior for the case?

chore: add a comment why fetcher accepts null

---

src/use-swr.ts

This is the last PR to fix all `react-hooks/exhaustive-deps` warnings.
The PR fixes the warnings in `useSWR`, which adds some deps for `memoizedState` and disables the rule for `revalidate`.
For `memoizedState`, I've added all deps in the deps array. `boundMutate` is an immutable function, so we can omit it, but I've added it to the deps array to enable `react-hooks/exhaustive-deps` rule. It's an immutable function, so it shouldn't be a problem.
For `revalidate`, I've disabled the `react-hooks/exhaustive-deps` rule because `fn` and `config` are defined as the arguments of `useSWR` call, which means those values would be changed every time.
I could add `eventsCallback`, `fnArgs`, `keyErr`, and `keyValidating` into the deps array. It should be safe because they only depend on `key` that is …

refactor: fix all react-hooks/exhaustive-deps warnings in useSWR

---

src/use-swr-infinite.ts
src/use-swr.ts

According to https://github.com/vercel/swr-site/pull/70#pullrequestreview-577603458, `revalidate()` will be deprecated in 1.x. I think it would be nice If it's commented as a source comment to tell the intention. It is helpful for contributors and developers who dig into the implementation.
Feel free to close this if it doesn't make sense 🙏

chore: add comments that revalidate will be deprecated

---

src/types.ts

Those types are for `useSWRPages`, which was an experimental API (never went public) and was replaced by `useSWRInfinite` in #435. So let's remove them.

Remove legacy useSWRPages types

---

test/use-swr-focus.test.tsx
test/use-swr-local-mutation.test.tsx

Fixes #940
I've inspected why the focus tests are flaky.
I've found that some tests didn't wait for a deduping interval, which means that a mutation in the next test might be deduped and failed.
To fix this, I've added `await act(() => sleep(1))` before the next mutation. But the intention of the code is very unclear, so I've separated it as another function called `waitForDedupingInterval`.
In addition, many of the current tests depend on a real timer, which makes tests flaky, so I've refactored to avoid depending on a real timer as much possible as I can by using `screen.findByText`.
I've also noticed that a test in `use-swr-local-mutation.test.tsx` is flaky, so I've fixed it too.
I think there are more flaky tests in SWR, so I'll fix them so that tests are more reliable. #932 and #933 …

test: fix flaky tests for focus and location mutation

---

test/use-swr-focus.test.tsx
test/use-swr-local-mutation.test.tsx

This addresses @shuding 's suggestion https://github.com/vercel/swr/pull/944#issuecomment-772009624.
I think `flushPendingUpdates` is also clear for the intention.

refactor: rename from waitForDedupingInterval to waitForNextTick

---

src/use-swr.ts

Fixes #953.
This seems to be caused by the change of  #889.
I've added the check if `document` is defined before SWR uses `document.addEventListener`.
The check is already being used at https://github.com/vercel/swr/blob/70ffd2c37dfed75ab703e70af1fdad666889f13f/src/libs/web-preset.ts#L14

fix: checking if document is defined

---

src/swr-config-context.ts
src/types.ts
src/use-swr-infinite.ts
src/use-swr.ts

This is a PR to make internal types (`fn`, `config`, and `key`)  more strictly.
This helps refactoring and code completion.
In the future, it would be nice if SWR could enable the TypeScript's `strict` mode.

types: makes types fn and config and key more strictly

---

src/use-swr.ts
test/use-swr-local-mutation.test.tsx

Fixes #975.
But I'm not sure what the expected behavior when `mutate` throws an error synchronously.
As #975 mentioned, currently the `mutate` function is cached as the data, which is definitely an unexpected behavior.
This PR makes SWR skip caching the data in this case.

fix: do not cache when mutate throws an error synchronously

---

src/config.ts
src/libs/web-preset.ts
src/types.ts
src/use-swr.ts

This PR separates DOM event handlers from `use-swr` and defined them in `web-preset`.
ref. https://github.com/vercel/swr/pull/963#issuecomment-773380777
These handlers are only used on browsers and SWR already has a file for browser APIs. So these handers should be placed in the file.
This would also make it possible to provide `defaultConfig` for each environment, which enables us to only include implementations that are required on the platform.

refactor: move DOM event handlers into web-preset

---

examples/infinite-scroll/README.md
examples/infinite-scroll/hooks/useOnScreen.js
examples/infinite-scroll/libs/fetch.js
examples/infinite-scroll/package.json
examples/infinite-scroll/pages/index.js

This example shows how to handle Infinite Scroll based on useSWRInfinite & IntersectionObserver
fixes #704

Add infinite scroll example using useSWRInfinite

---

src/config.ts
src/libs/web-preset.ts
src/types.ts
src/use-swr.ts

As @huozhi  mentioned https://github.com/vercel/swr/pull/972#issuecomment-783038279, I've renamed `onFocus` and `onConnect` to `registerOnFocus` and `registerOnConnect`.

refactor: add the register prefix to onFocus and onReconnect

---

src/use-swr.ts
test/use-swr-suspense.test.tsx

Fixes #454 
Currently, SWR doesn't apply the performance optimization mentioned in https://swr.vercel.app/advanced/performance with the `suspense` option, and it leads to unnecessary re-renders.
I've applied the same optimization using `stateDependencies` for the `suspense` mode.
Is there any reason not to apply the optimization for the `suspense` mode?
This is a fork of reproduction in https://github.com/vercel/swr/issues/454, which is based on this PR.
- https://codesandbox.io/s/swr-basic-forked-ftjio

perf: avoid unnecessary re-renders with the suspense mode

---

src/config.ts
src/libs/web-preset.ts
test/use-swr-focus.test.tsx
test/use-swr-offline.test.tsx

As mentioned in the code comments, `navigator.onLine` isn't always reliable due to [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=678075). Instead of depending on it, we have to use another approach to always assume it's online (since the page loads, it's _very likely_ to be online). And when we receive the `offline` event from `window`, we set the internal state to offline.
With this change, SWR will still try to revalidate even it's offline, if **both** requirements are meet: 
- the app is running with Service Worker (or RN), and it's offline. 
- Chrome (or the navigator) is having the bug mentioned above.  
It's an extremely rare case.
Also did some code optimizations (results in a smaller bundle with ncc) and updated tests.

Fix: do not depend on navigator.onLine; code optimizations

---

test/use-swr-config-callbacks.test.tsx
test/utils.ts

This PR is based on #932, so this should be merged after #932.
The following are the commits for this PR.
- https://github.com/vercel/swr/commit/59d37fc2f93968adce0fbfa613eb3437875a31e2
- https://github.com/vercel/swr/commit/489d9f47e34580f246c3bf1498797a0dcf6f2008
I've refactored `use-swr-config-callbacks.test.tsx` as the same way with #932.
But in this PR, I've added the `createResponse` function in `test/utils.ts`. This is used to create a `fetcher` function.
It's to minimize the usage of `setTimeout` because tests that depend on the actual time is fragile, so I think we should avoid it and wait for a promise for a response from a `fetcher` function.

 test: refactor use-swr-config-callbacks.test.tsx 

---

src/use-swr.ts
test/use-swr-refresh.test.tsx

fix: sync cache only on compare returns true

---

src/cache.ts
src/config.ts
src/index.ts
src/swr-config-context.ts
src/types.ts
src/use-swr-infinite.ts
src/use-swr.ts

This PR does 2 things:
1. The exported type `ConfigInterface` was changed in #946, which might be breaking. **However it's not released as stable yet**. This PR fixes it.
2. Renames some types to be more consistent. Also marks the old ones as deprecated. 
For 1, the cause is that properties in `ConfigInterface` are no longer optional. And if a user creates a custom hook the type might be broken:
```ts
import useSWR, { ConfigInterface } from 'swr'
function useData (opts: ConfigInterface) {
return useSWR('/api', opts)
}
useData({}) // ← error because all fields are required
```
For 2, updated types are:
| Current | New |
|:----|:---|
| `keyInterface` | `Key` |
| `ConfigInterface` | `SWRConfiguration` |
| `responseInterface` | `SWRResponse` |
| `SWRInfiniteConfigInterface` | …

Clean up types

---

src/use-swr.ts
test/use-swr-integration.test.tsx

This fixes #947.
SWR seems not to revalidate when having `initialData`.
> Another strange thing: when state contains empty string refetching happens. But if you change state to any string it returns initial data.
This PR doesn't fix the above that is also mentioned on #947.
I'll investigate it as another issue.

fix: revalidate with initialData when changing the key

---

src/use-swr-infinite.ts
src/use-swr.ts

Currently TS will show an error if you use `undefined` as the config: `useSWR('key', fetcher, undefined)`. It breaks the old behavior, which makes the following use case impossible:
```ts
import useSWR, { SWRConfiguration } from 'swr'
function useData (opts?: SWRConfiguration) {
useSWR('/api', fetcher, opts) // ⛔️
}
useData({}) // ✅
useData() // ⛔️
```

Allow passing undefined as the config

---

package.json
src/config.ts
src/libs/deep-equal.ts
yarn.lock

make swr core dependent less and light weight. the deep equal won't change much, now make as a vendor of swr lib.
* extract lite version of deep equal as lib
* remove dependency

Make swr zero dependency

---

test/use-swr-configs.test.tsx
test/use-swr-context-config.test.tsx

This is a followup PR of #933.
I've refactored tests for configs.

test: refactor tests for configs

---

src/cache.ts
src/use-swr-infinite.ts
src/use-swr.ts
test/use-swr-configs.test.tsx

Make the code cleaner and more consistent:
- use the `useState({})[1]` pattern for re-rendering the component
- make the internal property names shorter in `Cache`
- make the key prefixes in useSWRInfinite 3 chars (`ctx@`, `inf@`, `len@`), and internal cache property name shorter
- make `addRevalidator` return the ubsubscriber
Closes #896.

Micro optimizations

---

src/env.ts
src/libs/web-preset.ts
src/use-swr-infinite.ts
src/use-swr.ts
test/use-swr-config-callbacks.test.tsx
test/use-swr-configs.test.tsx
test/use-swr-infinite.test.tsx

fixes #976
This PR fixes issues caused by using multiple `useSWRInfinite` on a page.
You can see the issues in the following link (v0.42).
- **v0.42**: https://codesandbox.io/s/swr-basic-forked-nw6z4
- **THIS PR**: https://codesandbox.io/s/swr-basic-forked-uo7r0
This PR also fixes #976.
https://codesandbox.io/s/swr-basic-forked-mbx6y
I guess this is a naive implementation and would change some behaviors of `useSWRInfinite`, so it should be merged carefully.

fix: support multiple useSWRInfinite hooks in a page

---

src/use-swr-infinite.ts

An ESlint warning of `react-hooks/exhaustive-deps` is caused by https://github.com/vercel/swr/commit/b18414b901d60fbe63232537f298dc847ae20822 because the rule cannot determine `rerender` is always the same reference from `rerender = useState({})[1]`. Previously, this line was `[, rerender] = useState({})` and the rule can determine it is always the same reference.
To fix this, I've added `rerender` into the deps array because I'd like to enable the rule for the `setSize` function.

refactor: fix a react-hooks/exhaustive-deps warning

---

test/use-swr-config-callbacks.test.tsx
test/use-swr-focus.test.tsx

I've refactored `use-swr-focus.test.tsx`
I've also changed a timeout for a config callback test to make it more reliable.

test: refactor use-swr-focus.test.tsx

---

src/index.ts
src/use-swr.ts
test/use-swr-configs.test.tsx

To allow more flexible customisations and extensions it would be useful to export default config.
Eg. in our case we want to extend `onErrorRetry` but keep the current logic. Now we had to copy-paste the default config to our wrapper instead of calling it.

Export default SWR config to allow more flexible extensions

---

src/env.ts
src/use-swr.ts

Fixes #1046 #1050
```js
a = {
raf: window.requestAnimationFrame,
raf_pure: f => window.requestAnimationFrame(f)
}
f = () => console.log(1)
a.raf(f) // Error
// Chrome: Uncaught TypeError: Illegal invocation
// Firefox: Uncaught TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.
a.raf_pure(f) // log `1` in console
```
Possible root cause:
checked the repro in #1050, the line calling rAF is compiled to `c.rAF(n)`, rAF called on an object `c`, which represents a module. We need to make it pure.

fix: invalid invocation on raf

---

test/use-swr-loading.test.tsx

I've refactored use-swr-loading.test.tsx

test: refactor use-swr-loading.test.tsx

---

src/types.ts
src/use-swr.ts

Without this change, it is not possible for users to do `mutate<MyType>(...)`

Allow setting the generic on mutate()

---

package.json
src/libs/deep-equal.ts
src/state.ts
src/types.ts
src/use-swr.ts
test/use-swr-concurrent-mode.test.tsx
test/use-swr-key.test.tsx
test/use-swr-refresh.test.tsx
test/use-swr-suspense.test.tsx
yarn.lock

In swr, we have stateRef to store the data from the global cache.
1. In first render, stateRef will read data from cache then render it.
2. It will start a revalidation after the first mount and register an updater for the mutate function.
3. During the revalidation, if the fetcher gives new data, the cache and stateRef will update and it will schedule a rerender. So useSWR will return the fresh data
4. when mutate is called, the cache will update synchronously and updater will schedule a rerender to make useSWR return the fresh data
5. when key is changed, it will start a revalidation. repeat 3.
So if the fetcher or the mutate function makes useSWR rerender, the stateRef is always sync with the cache.
But if useSWR rerender because of the sibling hooks rerender or the parent component …

read cache during render

---

package.json

We're already using the minified version and I can't think of a specific case that you need to debug the lib itself (with minified code). It's also not enabled in previous versions so let's disable it.

Add `--no-sourcemap`

---

src/use-swr.ts
test/use-swr-local-mutation.test.tsx

cache cant update
https://codesandbox.io/s/swr-mutate-bug-eujb4?file=/src/index.tsx
inflight request should be ignored
https://codesandbox.io/s/swr-mutate-bug2-39199?file=/src/index.tsx
mutate should update data
https://codesandbox.io/s/useswr-async-mutate-bug-y77z1?file=/src/App.js
close #1070; close #1074;

Fix mutate

---

src/use-swr.ts
test/use-swr-revalidate.test.tsx

before:
after:
fix the above problem by utilizing `CONCURRENT_PROMISES_TS[key]` is undefined after executing `delete CONCURRENT_PROMISES_TS[key]`.
see added test case for detail.

fix: race problem when in dedupingInterval

---

test/use-swr-refresh.test.tsx

I've refactored use-swr-refresh.test.tsx.
The test file is the slowest test in `vercel/swr` because it has many tests depend on setTimeout/setInterval timers.
Reducing the interval of timers makes tests flaky, so I've used Jest's fake timers to reduce the total test time.
- Before
```
➜  yarn test                                                                                                                                                                                                                 
yarn run v1.22.10
$ jest
PASS  test/use-swr-config-callbacks.test.tsx
PASS  test/use-swr-concurrent-mode.test.tsx
PASS  test/use-swr-revalidate.test.tsx
PASS  test/use-swr-key.test.tsx
PASS  test/use-swr-configs.test.tsx
PASS  test/use-swr-focus.test.tsx
PASS …
```

test: refactor use-swr-refresh.test.tsx

---

examples/optimistic-ui-immer/pages/index.js
examples/optimistic-ui/pages/index.js

From my understanding the two examples of optimistic UI have the same behavior: they update optimistically, and then send a POST request, and update again according to the backend reply, if it replies.
The comments in the example `index.js` seem misleading (at least it was for me):
For optimistic UI we have [this comment](https://github.com/vercel/swr/blob/master/examples/optimistic-ui/pages/index.js#L13):
```javascript
// the fetch below could fail, in that case the UI will
// be in an incorrect state
```
For optimistic UI with Immer.js we have nothing about possible fetch failure, but we have [this comment](https://github.com/vercel/swr/blob/master/examples/optimistic-ui-immer/pages/index.js#L21):
```javascript
// if this fail it will rollback the optimistic update
```
I think we should …

Optimistic UI examples comments clearer

---

src/use-swr-infinite.ts
src/use-swr.ts
test/use-swr-local-mutation.test.tsx

We call `cache.set(pageSizeCacheKey, persistSize ? lastPageSizeRef.current : initialSize)` inside `useSWRInfinite` whenever the `firstPageKey` changes, but the key can still be `null`. In that case we are setting `cache.set(null, 1)` which should be avoided.

Fix setting `null` cache in `useSWRInfinite`

---

test/use-swr-revalidate.test.tsx

I've refactored use-swr-revalidate.test.tsx.

test: refactor use-swr-revalidate.test.tsx

---

examples/axios-typescript/libs/useRequest.ts

My VSCode shows warnings that `responseInterface`, `ConfigInterface` are deprecated which are used in axios-typescript example. I noticed that they have `@deprecated` annotations in type definition file and were described they will be renamed to `SWRResponse`, `SWRConfiguration` each other. 
So I replaced them with latest types(`SWRResponse`, `SWRConfiguration`) already existing.

Replace deprecated types with latest types in axios-typescript example

---

src/config.ts

Use slow connection mode when `navigator.connection.saveData` is enabled
https://github.com/vercel/swr/issues/1122

slow connection mode when `navigator.connection.saveData` is enabled

---

src/use-swr.ts

Clean code since `key` is ensured to be true.
https://github.com/vercel/swr/blob/f7876240094c02c9933757d3e8d568185122adfb/src/use-swr.ts#L63-L67

clean code

---

README.md

The bounded mutation example doesn't immediately mutate the cache, instead its waiting for the request to come back and then updating the cache. 
I think making this example similar to the one above, where we are trying to optimistically update the local state is a more consistent example

Update bound mutate readme

---

package.json

Adopt [exports sugar](https://nodejs.org/api/packages.html#packages_exports_sugar), to make subpath imports like `swr/infinite` easier in long run.
parsing `exports` field is supported in webpack5.

enhance: support exports field

---

examples/autocomplete-suggestions/package.json

Fixes #1129 
The issue is caused by `@reach/combobox`, so I've updated the version to fix it.

fix: autocomplete suggestions example

---

src/libs/web-preset.ts

In React Native environments, window refers to `global` object but `window.addEventListener` does not exit, so we need to check window.addEventListener exists too in addition to `window` existence to allow running in React Native environments.
ref. https://stackoverflow.com/questions/49911424/what-does-the-variable-window-represent-in-react-native
This incompatibility with RN was accidentally introduced in this PR.
https://github.com/vercel/swr/commit/b38d1bd74d4afc3ae4f43e732b573f5dfd89211d#diff-8e1a842791533fc5b3bd3a489a491864e056b3ddd867b208e566d05319175860L27

Fix: Make SWR compatible with React Native again (window.addEventListener.bind fails)

---

package.json
src/env.ts
src/libs/web-preset.ts
src/use-swr-infinite.ts
src/use-swr.ts
yarn.lock

This PR bumps typescript to 3.9.10 so that we can use `ts-expect-error` instead of `ts-ignore`. 
I've tried to bump typescript to the latest version, but the build with `bunchee` was failed. To fix this, I would have to update some dependencies that `bunchee` has and I'll work on it later.

chore: bump typescript to use ts-expect-error instead of ts-ignore

---

src/libs/hash.ts
src/libs/serialize.ts
src/use-swr-infinite.ts

specialize keys for `error` and `isValidating`, and some non major keys in swr infinite, to identify them easier later if developers want to play tricks with keys or filter them from cache provider.
Resolves #242 
e.g.
```js
const provider = new Map()
const { cache, mutate } = createCache(provider)
// ...
const serializedKeys = Array.from(provider.keys()).filter(k => !k.startsWith('$'))
```
```js
const validatingKeys = serializedKeys.filter(key => key.startsWith('$req$'))
```

enhance: add $ prefix for non-major keys

---

src/utils/env.ts

`navigator` doesn't exist on the Node environment, so it is required to check if `navigator` is not undefined.

fix: fail accessing navigator on Node

---

immutable/tsconfig.json
infinite/tsconfig.json
package.json

Currently, `yarn build` is failed when the `dist/` directories already exist, so I've added `dist/` directories into the `exclude` setting to ignore them. I've also remove them on the `prepublishOnly` script.

chore: fix to run the build script multiple times

---

package.json
test/use-swr-concurrent-rendering.test.tsx
yarn.lock

React has announced that they released v18 alpha, so I think it's better to use an alpha version rather than an experimental version.
https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html
I've also fixed API changes in the alpha version.

test: run concurrent rendering tests with React v18 alpha

---

.eslintignore

I've had the following error while running `yarn lint`, which is caused by checking .d.ts files in `dist/`. So I've ignored them.
```
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: immutable/dist/src/index.d.ts.
The file must be included in at least one of the projects provided
```
I've also removed unnecessary ignored targets.

fix: ignore .d.ts in dist/ for ESLint

---

.codesandbox/ci.json
jest.config.js
package.json
test/use-swr-refresh.test.tsx
tsconfig.json
tsconfig.test.json
yarn.lock

Closes #1256 
* Use ts source files for testing
* upgrade jest suite, jest 27 requires setting test version to `jsdom`

enhance: use ts for testing

---

package.json

~This is an alternative of #1256 
Currently, we have to build each packages to run tests, which is a bit cumbersome,  and I've added npm-scripts to watch and build each package.~
~With this PR, we don't have to run a build script manually for unit testing.~
I've reopened this because I think this is useful to use local builds to run an application.

chore: add watch scripts for sub packages to build them

---

src/types.ts

Fix: `SWRHookWithdMiddleware` -> `SWRHookWithMiddleware`

Fix typo of type SWRHookWithMiddleware

---

infinite/index.ts
infinite/types.ts
src/index.ts
src/types.ts
src/use-swr.ts

```diff
- import { SWRInfiniteConfiguration, SWRInfiniteResponse } from 'swr'
+ import { SWRInfiniteConfiguration, SWRInfiniteResponse } from 'swr/infinite'
```

Move infinite types to swr/infinite and deprecate old ones

---

src/utils/env.ts

For Deno, `window` is `globalThis`, so `Deno === window.Deno === globalThis.Deno`. Ignore the case that user customized their own global variable `window.Deno = xxx`

enhance: simplify deno detection

---

src/types.ts
src/use-swr.ts
src/utils/config.ts
src/utils/web-preset.ts
test/use-swr-cache.test.tsx
test/use-swr-focus.test.tsx
test/use-swr-immutable.test.tsx
test/use-swr-integration.test.tsx
test/use-swr-local-mutation.test.tsx
test/use-swr-offline.test.tsx
test/use-swr-revalidate.test.tsx
test/utils.ts

Fixes #1275
* Only need to `setupOn<Event>` for cache
* Setup global listeners inside `createCache` 
```js
createCache(new Map(), {
// if you want to override any event that can trigger revalidation, use following options
// override default behavior of revalidate on focus, it will revalidate on your own `focus` event now
setupOnFocus(focusRevalidator) {
customEvent.on('focus', focusRevalidator)
},
// override default behavior of revalidate on reconnect, it will revalidate on custom network events now
setupOnReconnect(reconnectRevalidator) {
customEvent.on('reconnect', reconnectRevalidator)
}
})
```
* Fix custom cache is not bound to env like `focus`, `reconnect` events on web

Refine createCache

---

infinite/index.ts
jest.config.js
test/use-swr-infinite.test.tsx

By design, we should always revalidate the first page even if `force` is set to `false`.
Closes #908. Also added a test case.

Fix useSWRInfinite doesn't revalidate the first page

---

.github/workflows/test.yml
src/types.ts
src/use-swr.ts
src/utils/cache.ts
src/utils/state.ts

The most significant change is to move event setup and global states into the cache wrapper, so the main logic (use-swr.ts) keeps uncoupled.

Code structure refactoring

---

README.md
src/types.ts
src/utils/config.ts
test/use-swr-integration.test.tsx
test/use-swr-local-mutation.test.tsx

Breaking: drop the default fetcher

---

src/types.ts
src/use-swr.ts
src/utils/config.ts
src/utils/web-preset.ts

To make the option meaning more general, and shorter for convenience, rename `isDocumentVisible` to `isVisible`

Rename isDocumentVisible to isVisible

---

src/utils/normalize-args.ts
test/unit.test.tsx

When `args[1]` is `null`, `typeof args[1]` will still be `"object"` which causes this bug.
Fixes #1274.

Fix config being ignored when fetcher is null

---

infinite/index.ts
test/use-swr-infinite.test.tsx

One notable change is that we no longer use an object to pass the context to fetcher: `{ data: originalData, force: false }`, instead an array is used `[false, originalData]`.
The test also ensures that #590 is fixed.

Chore: code refactoring, comment and test improvements for useSWRInfinite

---

test/use-swr-infinite.test.tsx

I've added a test for `getInfiniteKey` with current data to cover https://github.com/vercel/swr/pull/1257#issuecomment-890263566

test: add a test for getInfiniteKey with current data

---

package.json
yarn.lock

typescript is now a peer dep of bunchee, the node modules install size should be reduced around 50+MB. from 415MB to 360MB

upgrade bunchee, reduce node_modules size

---

examples/axios-typescript/libs/useRequest.ts
examples/focus-revalidate/pages/index.js
examples/refetch-interval/pages/index.js
infinite/index.ts
src/types.ts
src/use-swr.ts
test/use-swr-config-callbacks.test.tsx
test/use-swr-integration.test.tsx
test/use-swr-revalidate.test.tsx

* remove returned `revalidate`
* update related examples

BREAKING CHANGE: deprecate revalidate

---

infinite/index.ts
test/use-swr-infinite.test.tsx

Currently `useSWRInfinite` will always fetch new pages (when `setSize` is called), even if it's already cached by `useSWR` or something outside of that "pages" cache (an array of pages). With this PR we only re-fetch if the previous cached data of _that page_ has changed. 
Check the test case to see the detailed behavior.

Improvement: ensure `useSWRInfinite` reuses `useSWR` cache

---

src/types.ts

It should allow calling `mutate()` without an argument.

Fix argument type of `MutatorCallback`

---

infinite/index.ts
test/use-swr-infinite.test.tsx

Right now `useSWRInfinite` directly revalidates after changing its page size. If that revalidation awaits due to some reason, you can't immediately get the new resized page array even if everything is already in the cache.
This PR changes the behavior to use `mutate` to first return the stale page array with the updated size, and then revalidate in the background.

Improvement: return stale data then revalidate when setting size of `useSWRInfinite`

---

infinite/index.ts
src/index.ts
src/use-swr.ts
test/use-swr-infinite.test.tsx

SWR handles key serialization so it can just pass a string to the cache provider. This makes all the interfaces simpler. However it makes getting data from the cache (or mutating a specific key) tricky, because the serialization util isn't exposed as an API.
Previously we had #1257 to expose the serialization of the `useSWRInfinite` key. This PR unifies the API name, as well as exposing the `serialize` API of `useSWR`.
Related: #1324, #1257.

Export `unstable_serialize` from SWR

---

package.json

* run type checking on `pre-push` git hook, to speed up local development
* fix prettier, lint command with lint-staged for changed files only

lint-staged: remove lint, fix prettier

---

.gitignore
CONTRIBUTING.md
examples/infinite/package.json
package.json
scripts/dev-next.js
scripts/require-hook.js

The local development commands now fails to run for me. cc @promer94 
Figure out another way to develop swr with local existing examples, checkout the readme change.
In short, you can run `yarn dev-next <example name>` to run it with next.js. No extra dependencies required.

Local devdelopment with examples

---

scripts/dev-next.js
scripts/next-config.js

The swr in client bundle is not the one been aliased. reported by @promer94  
Add process to override swr assets by using `next.config.js`:
* run dev command
* create symblink for swr assets overriding
* quit dev command
* unlink custom `next.config.js` and kill dev server

fix: alias swr in next client bundle on dev mode

---

.eslintrc
src/types.ts
src/use-swr.ts
src/utils/cache.ts
src/utils/config.ts
src/utils/subscribe-key.ts

- Organize revalidation callbacks into `RevalidateCallback` and `StateUpdateCallback`. The revalidate callback receives internal event (`onfocus`, `onreconnect`, `onmutate`) that might trigger a revalidation to the hook. The state update callback handles hooks' `setState` events. This is the initial step for some future features.
- The new subscribe-key util makes the core leaner.
- Other tweaks.

Refactor code structure

---

src/utils/resolve-args.ts
test/use-swr-middlewares.test.tsx

Middleware should be wrapped and executed from the outside to the inside.

Invert middleware execution order

---

src/types.ts
src/utils/config-context.ts
src/utils/merge-config.ts
src/utils/resolve-args.ts
src/utils/with-middleware.ts
test/use-swr-config.test.tsx
test/use-swr-middlewares.test.tsx

middleware can be singular or plural. rename it to `use` as short and clear. (Aother popular library like expressjs choosed `router.use()` api)

Rename middlewares option to use

---

test/use-swr-cache.test.tsx

A new test case with some improvements made to existing ones.

Chore: improve tests for cache provider

---

infinite/index.ts
src/use-swr.ts
src/utils/web-preset.ts
test/use-swr-loading.test.tsx

Change `Object.defineProperties` to object getter. Also added a test to ensure object properties are enumerable.

Replace Object.defineProperties with getter 

---

test/use-swr-immutable.test.tsx
test/use-swr-node-env.test.tsx

Add basic test suites for running on node env

Add basic test for node env

---

infinite/index.ts
test/use-swr-infinite.test.tsx

[Infinite] Return current data if failed to resolve pages from cache when setting size

---

immutable/index.ts
src/types.ts
src/use-swr.ts
src/utils/config.ts
test/use-swr-immutable.test.tsx

Both have the same meaning, but "if" is close to the HTTP cache control naming conventions ("only-if-cached", "stale-if-error").

Rename revalidateWhenStale to revalidateIfStale

---

src/use-swr.ts
test/use-swr-error.test.tsx

Fixes #1395.
I guess SWR should update the cache value for `isValidating` when an error occurred.

fix: isValidating when an error occurred

---

src/use-swr.ts
test/use-swr-suspense.test.tsx

Fixes #1359.
I've added a warning for invalid arguments with suspense mode.
The check (`!key || !fn`) is the same validation used in other places.

feat: add a warning for invalid arguments with suspense mode

---

src/index.ts

This is necessary to type the `mutate` method returned by the hook. It is useful when passing it around for example into a custom context.
> NOTE: The deprecated `revalidate` method had a type of `Promise<boolean>`. 
When replacing `mutate` with `revalidate`, we now needed to do this:
```
import type { KeyedMutator } from "swr/dist/types"
...
revalidateAccount: KeyedMutator<AxiosResponse<User>>
```
With this PR, the above code becomes:
```
import type { KeyedMutator } from "swr"
...
revalidateAccount: KeyedMutator<AxiosResponse<User>>
```
Which is nicer when working with the other type exported.

chore: Export KeyedMutator type from root export

---

src/use-swr.ts
test/use-swr-local-mutation.test.tsx

Fixes #1407
cache should be updated before `setState`

fix: isValidating cache inconsistence in mutatation

---

test/use-swr-error.test.tsx
test/utils.tsx

This is a PR to propose to make unit tests more reliable.
Currently, most of the tests depend on a global cache store, which means that those tests share the same cache. This is fragile because the tests might start failing when we use the same key in between them.
SWR has `createKey` as a utility function for testing to generate a random key, which would solve the problem, but I think running tests on independent environments is important and makes tests more reliable.
To fix this, I've added `<TestSWRConfig />`, which creates its own cache provider, and wrapped target components in it. We don't have to care about duplicating keys while using `<TestSWRConfig />`.
I used the name because I expect to be added more configurations for testing in the component. More explicit names like …

refactor: use TestSWRConfig for error-test

---

test/use-swr-cache.test.tsx

I've refactored tests for errors at #1404 to use a custom cache for each test, and will refactor other tests as well. Before doing that, I've added tests for the global cache not to break the behaviors of the global cache.

test: add tests for a global cache

---

src/use-swr.ts
src/utils/web-preset.ts

* use config ref in `execute` function
* shorten generated code (8016 -> 8582)

Chore: always use config ref

---

src/constants/revalidate-events.ts
src/types.ts
src/use-swr.ts
src/utils/broadcast-state.ts
src/utils/cache.ts
test/use-swr-focus.test.tsx

Resolves #1420 
Checked the bundle size is consistent

typing: use separated constants instead of enum

---

src/use-swr.ts
test/use-swr-immutable.test.tsx

With the added test, currently 4 requests will be made because a SWR hook will always revalidate when the key changes. However the correct behavior should be treating a key change as a "remount", and using the `shouldRevalidateOnMount` condition to decide if a revalidation is necessary.

Fix revalidateIfStale behavior when the key changes

---

test/use-swr-error.test.tsx
test/utils.tsx

I've introduced `TestSWRConfig`, which is a wrapper component for unit tests, and applied it to `use-swr-error.test.tsx` to avoid using a global cache shared between each test.
While refactoring other tests using the components, I've realized that this approach has a major flaw.
The downside of the approach is that it's very hard to guarantee all components passed to the `testing-library`'s render function are wrapped by `TestSWRConfig`. I sometimes missed placing the component while refactoring tests.
I might be able to check this mistake statically using ESLint or something, but I think it introduces another complexity.
So I reconsidered the approach and took another approach. The following is what I thought. Feedbacks are welcome!
If it seems to be good, I'll refactor each test as …

test: add render utilities and remove TestSWRConfig

---

jest.config.js
src/types.ts
test/use-swr-immutable.test.tsx

Some tsc errors aren't been captured
```
@rollup/plugin-typescript TS2322: Type 'readonly Data[] | undefined' is not assignable to type 'Data[] | undefined'.
The type 'readonly Data[]' is 'readonly' and cannot be assigned to the mutable type 'Data[]'.
Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `swr["default"]` to access the default export, which may not be what you want. Use `outpu
t.exports: "named"` to disable this warning
@rollup/plugin-typescript TS2345: Argument of type '{ mutate: boolean; }' is not assignable to parameter of type 'RevalidatorOptions'.
Object literal may only specify known properties, and 'mutate' does not exist in type 'RevalidatorOptions'.
@rollup/plugin-typescript TS2345: Argument of type '{ …
```

Revert "Feature: make return state(data, error and isValidating) readonly"

---

package.json
tsconfig.json
yarn.lock

* jest 27 has built-in types
* node types is not really been used

chore: remove unused typings

---

src/types.ts
src/use-swr.ts
src/utils/cache.ts
src/utils/config-context.ts
src/utils/config.ts
src/utils/web-preset.ts
test/use-swr-cache.test.tsx
test/use-swr-concurrent-rendering.test.tsx

Support release handler
```js
initFocus: (revalidate) => {
addFocusHandler(revalidate)
return () => {
removeFocusHandler(revalidate)
}
}
```

enhance: provider release handlers

---

src/utils/cache.ts
src/utils/config-context.ts

- Fix typo (`unscubscibe`)
- `unsubscribe` is always a function so no need to check again
- Other tweaks

Chore: refactor code related to unsubscribing global listeners

---

test/use-swr-concurrent-rendering.test.tsx
test/utils.tsx

concurrent rendering tests are different from other tests because they render components with `ReactDOM.createRoot`, so I didn't use `renderWithConfig` in `test/utils.tsx`.
I've also noticed that the render function of `testing-library` has the `wrapper` option to wrap a target component. 
https://testing-library.com/docs/react-testing-library/setup#custom-render
With the option, we no longer require to override `rerender` function to wrap a target component with `SWRConfig`. It's less hacky than before, so I've refactored to use it.

test: refactor concurrent rendering tests

---

test/use-swr-config-callbacks.test.tsx
test/use-swr-config.test.tsx

This is a follow-up PR of #1435

test: refactor config tests

---

src/utils/web-preset.ts

Closes #1453
`addEventListener` needs to be called from `document` in IE11. Otherwise you'll run into a `Invalid calling object` error.
I've tested the proposed changes in IE11 and couldn't find any other errors.

fix: Support IE11

---

test/use-swr-integration.test.tsx
test/use-swr-loading.test.tsx

test: refactor integration and loading tests

---

test/use-swr-key.test.tsx
test/use-swr-middlewares.test.tsx
test/use-swr-suspense.test.tsx

test: refactor key, middlewares, and suspense tests

---

package.json
yarn.lock

Upgrade ts to v4.4.3
There's a problem that we have to resolve tslib to 2.3.0 for both bundling and linting. The dep `tsutil` of typescript eslint is still resolving tslib v1, which will break the linting.

Upgrade typescript to 4.4.3

---

src/use-swr.ts
src/utils/broadcast-state.ts
src/utils/mutate.ts
src/utils/web-preset.ts

- Renames `shouldRevalidate` to just `revalidate`
- Binds event listener registers
- Changes the `shouldDedupe` logic as `shouldStartNewRequest`

chore: Code refactoring

---

.gitignore
tsconfig.json

Current `types:check` script will skip sub folders like `inifinite` etc. tweaks some ts configuration include sub folders

ci: multiple dir type checking

---

infinite/index.ts
infinite/types.ts
src/index.ts
src/types.ts
src/utils/cache.ts
src/utils/config-context.ts
src/utils/web-preset.ts

Based on #1477, this PR refines some of the internal and exported type names and interfaces:
- Exported `ValueKey` → `Arguments` for accuracy
- Exported `Result` → removed, as it's a simple `T | Promise<T>` wrapper
- New exported `InfiniteKeyLoader` from `swr/infinite`, we can deprecate `KeyLoader` of `swr` later
- Rename internal type name `Args` to `SWRKey` for accuracy
- Other code refactoring

chore: Refine type interfaces

---

.gitignore
package.json
yarn.lock

This makes the pre-commit hook a lot faster (12s → 2s).

chore: Upgrade eslint and add local cache

---

src/types.ts
src/use-swr.ts
src/utils/config.ts
test/use-swr-config-callbacks.test.tsx

This new callback will be triggered when the request result is discarded due to race conditions (in the future, it will also be used as the request cancelation/abortion callback too).

feat: Add new onDiscarded option

---

src/use-swr.ts
test/use-swr-error.test.tsx

Currently the `onError` and `onErrorRetry` events are also fired for deduped requests. This behavior should be aligned with the `onSuccess` and `onLoadingSlow` events: https://github.com/vercel/swr/blob/eb55c8c1f446724b022dfb0c18cc004d6a8b9d01/src/use-swr.ts#L193-L202

fix: Error events should be deduplicated

---

src/use-swr.ts
test/use-swr-config-callbacks.test.tsx

This PR moves the `onSuccess` event callback down, so it will not be called if the request result was discarded due to race conditions.

fix: Only trigger the success event if not discarded

---

src/utils/with-middleware.ts

- Enable users to use shared config objects across useSWR, useSWRInfinite without the React rule of hooks error
closes #1555

fix: change config alteration process in withMiddleware to be immutable

---

immutable/package.json
infinite/package.json
jest.config.js
package.json

Fixes: #1614
Fixes: #1617
Revert "chore: Add type: "module" and use .mjs extension (#1604)"

Revert "chore: Add type: "module" and use .mjs extension (#1604)"

---

infinite/types.ts
src/index.ts
src/types.ts
test/type/fetcher.ts

* make ```useSWR<{ id: number }>('/api/', (key) => ({ id: 123 }))``` still works as before 
so users dont need to update their current code
* add test case for #1586 
* remove some comments (replace with ts playground link later)

Tweak types

---

src/utils/env.ts

Fixes: #1657 
It works fine without the polyfill settings mentioned in the issue above.
Instead of importing the rAF function at the moment of import, the function that meets the condition is imported when necessary.

fix: supports ssr in ie11(#1657)

---

src/types.ts
src/use-swr.ts
test/use-swr-refresh.test.tsx

Closes #1683 
In addition to passing a number, `refreshInterval` can also receive a function that returns a number as an interval. The function has access to the updated data.
Do I need to add anything to the examples folder? I'd like to update the docs as well, but it's in a different repo.
- Function can be passed to `refreshInterval`
- Data passed to `refreshInterval`  is updated data

feat: refreshInterval as a function

---

test/use-swr-refresh.test.tsx

Related to #1690 
Add test when `refreshInterval` function returns 0 for the interval. The `refreshInterval` should be disable, which is the same as using `refreshInterval` with a number.
I keep it simple because there are tests for updated data and passing function as an interval. Alternatively, I can make the count goes down from 2 to 0 to demo it is working initially before being disabled.

test: add refreshInterval function returns 0

---

src/use-swr.ts
test/use-swr-loading.test.tsx

fix: If `newData` is deeply to the latest state, broadcast the latest state

---

src/use-swr.ts
test/use-swr-config.test.tsx
test/use-swr-suspense.test.tsx

fix: Return `undefined` data if key's falsy under suspense mode

---

infinite/index.ts
infinite/types.ts

Hi, this PR simply exports two types: `SWRInfinteHook` and `InfinteKeyLoader`.
For `InfiniteKeyLoader` I have this use case.
```ts
const keyLoader: InfiniteKeyLoader = (index, previousPageData) => { /* ... */ };
export const useList = () => {
const { data } = useSWRInfinite(keyLoader, fetcher);
// ...
};
export const revalidateList = () => mutate(unstable_serialize(keyLoader));
```
I saw `SWRHook` is exported in `swr` so I added `SWRInfinteHook` as well. Thanks!

type(infinite): export SWRInfinteHook and InfiniteKeyLoader from infinite

---

src/utils/cache.ts
src/utils/web-preset.ts
test/use-swr-cache.test.tsx
test/use-swr-focus.test.tsx

Most of the time, the "refocus" event also comes with a "click" which as a result can cause React state changes. Currently SWR revalidates synchronously on page focus (and network recovery too), but a React state change can make that revalidation unnecessary. #1680 is a good example.
Similar to the `rAF` improvement we added for `revalidateOnMount`, we can delay these auto revalidations a bit.
Closes #1693, closes #1680.

feat: Ensure auto revalidations are executed after state updates

---

src/use-swr.ts
test/use-swr-fetcher.test.tsx

Here we are adding a reference of the latest `fetcher` parameter and whenever a revalidation executes, that latest reference should be used. Detailed use case can be found in #1131.

feat: Use the latest reference of fetcher

---

infinite/index.ts

As mentioned [here](https://github.com/vercel/swr/pull/1714#issuecomment-1000526182), we are adding back `InfiniteFetcher` to avoid breaking changes.

fix: Re-export InfiniteFetcher

---

src/index.ts
src/types.ts
src/utils/broadcast-state.ts
src/utils/mutate.ts
test/use-swr-local-mutation.test.tsx

This is cherry-picked from #1450. Currently we only support 2 types of `mutate` calls:
1. `mutate()`
2. `mutate(data, revalidate = true)`
This PR extends the second parameter with another option:
```js
mutate(data, {
populateCache: boolean = true
})
```
If disabled, `data` will not be written to the cache. The `revalidate` behavior can also be controlled here too:
```js
mutate(data, {
revalidate: boolean = true,
populateCache: boolean = true
})
```
_Note that this is the initial step for #1450, and other future improvements for optimistic UI (#1721)._

feat: Add `populateCache` option to `mutate`

---

src/use-swr.ts
src/utils/broadcast-state.ts
src/utils/cache.ts
src/utils/global-state.ts

Use one object to store all states for concurrent requests, currently the promise and the timestamp. Later we will add more fields to it to handle callbacks more correctly.

Merge states for concurrent requests

---

jest.config.js
src/index.ts
src/use-swr.ts
src/utils/config.ts
src/utils/web-preset.ts
test/unit/serialize.test.ts
test/use-swr-error.test.tsx
test/use-swr-reconnect.test.tsx
test/utils.tsx

- Skip error retrying when document is not active
- Improve test coverage

Skip error retrying when document is not active and improve tests

---

src/types.ts
src/utils/broadcast-state.ts
src/utils/mutate.ts
test/use-swr-local-mutation.test.tsx

This PR a adds two more options to `mutate`, `rollbackOnError` and `optimisticData`:
```js
mutate(updateUser(user), {
revalidate: true,
populateCache: true,
rollbackOnError: true,
optimisticData: user,
})
```
Here `updateUser(user)` is a promise or async function to actually do the **remote mutation**, and `optimisticData` is the value for immediate and **optimistic update**.
When `populateCache` is disabled, the result of that remote mutation will not be written to the cache. 
And if `rollbackOnError` is enabled, and the remote mutation errors (the promise rejects), the previously updated optimistic data will be rolled back.
And overall, using the mutate API can avoid race conditions from normal `useSWR` requests.
A detailed example: …

feat: Optimistic mutation with error rollback

---

src/use-swr.ts
src/utils/broadcast-state.ts
src/utils/cache.ts
src/utils/global-state.ts
src/utils/mutate.ts

Similar to #1741, we are using one slot to keep all mutation related states.

chore: Merge mutation states

---

src/use-swr.ts
src/utils/mutate.ts
src/utils/serialize.ts
test/use-swr-local-mutation.test.tsx

This PR gets rid of the error and isValidating cache keys and use one single key to track both states. In 2.0 we will also merge data into it and directly use the unmodified cache key.

Merge extra request states in cache

---

immutable/package.json
infinite/package.json
package.json
yarn.lock

* Add `exports.module` condition for `.esm.js` extensions
* Change `exports.import` condition to `.mjs` extensions
At the same time we still have `module` field as fallback. In this case, bundler can pick the field which it supports.
Closes #1758
Closes #1759 
* Create a dummy package wrapping on top of swr, let's call it `module-swr`
```json
// package.json
{
"exports": "index.js",
"type": "module",
}
```
```js
// index.js
export * from 'swr'
export {default} from 'swr'
```
integrate with following app starter, import `useSWR` hook from `"module-swr"`
1. CRA 5 ✅
2. React Native CLI (metro bundler) ✅
If you're playing with RN (metro bundler), you can not directly use mjs extension files if you're trying to wrap swr since mjs is not supported yet.

build: support mjs exports

---

package.json

follow up: #1760 
RN can pick other exports fields

chore: remove useless react-native field

---

src/utils/resolve-args.ts

Related #1768
react devtool now parses all the function calls so polish the anonymous function name to a readable one
After

polish: display name in devtool

---

examples/api-hooks/README.md
examples/autocomplete-suggestions/README.md
examples/axios-typescript/README.md
examples/axios/README.md
examples/basic-typescript/README.md
examples/basic/README.md
examples/focus-revalidate/README.md
examples/global-fetcher/README.md
examples/infinite-scroll/README.md
examples/infinite/README.md
examples/local-state-sharing/README.md
examples/optimistic-ui-immer/README.md
examples/optimistic-ui/README.md
examples/prefetch-preload/README.md
examples/refetch-interval/README.md
examples/server-render/README.md
examples/storage-tab-sync/README.md
examples/suspense/README.md
package.json
yarn.lock

This PR fixes incorrect deploy links and docs in examples, also upgrades @swc-node/jest to the latest version which should be a bit faster.

chore: Update examples and dependencies

---

jest.config.js
package.json
yarn.lock

`@swc/core` is a peer dep of `@swc/jest`, unlike `@swc-node/jest` uses it as a dep. We could share it as a common version later if we still use it for other purposes.

test: use @swc/jest

---

.eslintignore
.eslintrc
.gitignore
.npmignore
.prettierrc
.yarnrc
package.json

- .eslintignore can be merged into .eslintrc
- .npmignore is already a subset of .gitignore
- .yarnrc is not needed as SWR has only dev dependences, safe to use the `^` semver matcher
- .prettierrc can be merged into package.json
Also improved package.json a bit.

chore: Clean up configurations

---

src/use-swr.ts
test/use-swr-fetcher.test.tsx
test/use-swr-infinite.test.tsx

fixes #1776
This is similar to #1727, but this is for the suspense mode.
#1776 seems to be caused by the stale `getKey`, which is referenced from the stale `fetcher` function.
This mutates the fetcher and config ref objects in rendering, but I think it's not a desirable way, so I should probably find out another way.

fix: use the latest reference of fetcher with suspense mode

---

infinite/index.ts
test/use-swr-infinite.test.tsx

Fixes #1804
This fixes `useSWRInfinite` revalidates on mounting with `revalidateOnMount` option.

fix: useSWRInfinite revalidates with revalidateOnMount

---

src/use-swr.ts

Please correct me if I'm wrong 🙏
The documentation of `revalidateIfStale` says that "automatic revalidation on mount even if there is stale data", but according to the current implementation, the `revalidateIfStale` option has an effect on updates, doesn't it?
https://swr.vercel.app/docs/options#options
If so, I'll send a PR for that.
In this PR,  I made three changes that I've noticed while reading the implementation.
1. The [`shouldRevalidateOnMount`](https://github.com/vercel/swr/blob/c63cafcb00f78af1d16ef5649d7c26d396c46de9/src/use-swr.ts#L446) function has an effect on updates, not only mounting. So I feel `shouldRevalidate` is the appropriate name for the function.
2. In the `shouldRevalidate` function, the `revalidateOnMount` option should be changed only when mounting, so I've …

refactor: revalidateIfStale has an effect on updates, not only mounting

---

src/use-swr.ts
test/use-swr-suspense.test.tsx

Fix #1836 
* key changes from `foo` to `''`
https://github.com/vercel/swr/blob/01e05946e22edbfbfd63eff9b8617d7c6283992c/src/use-swr.ts#L461
* Then key changes from `''` to `bar`
* In suspense mode,
https://github.com/vercel/swr/blob/01e05946e22edbfbfd63eff9b8617d7c6283992c/src/use-swr.ts#L433 
***would not be executed***
* So fetcher will not have chance to update the cache
https://github.com/vercel/swr/blob/01e05946e22edbfbfd63eff9b8617d7c6283992c/src/use-swr.ts#L134-L141

fix: reset stale unmountedRef in suspense

---

test/use-swr-integration.test.tsx

This is a follow-up PR of #1837.
I've added a test that `revalidteOnMount: false` should call the fetcher function when the key has been changed.

test: add a test for the behavior of revalidateOnMount when the key has been changed

---

src/use-swr.ts
test/use-swr-suspense.test.tsx

Today, `revalidateIfStale` is ignored when using `suspense: true`.
This fix makes `revalidateIfStale` behave consistently with or without `suspense`

bugfix: make suspense and revalidateIfStale work together

---

src/types.ts
src/utils/mutate.ts
test/use-swr-local-mutation.test.tsx

feat: support functional optimisticData

---

test/use-swr-local-mutation.test.tsx

This fixes the `act` warning that you can see at https://github.com/vercel/swr/runs/5253406383?check_suite_focus=true

test: fix an act warning

---

infinite/index.ts
infinite/types.ts
src/types.ts
src/use-swr.ts
src/utils/serialize.ts
test/type/fetcher.ts
test/type/option-fetcher.ts
test/use-swr-infinite.test.tsx
test/use-swr-integration.test.tsx
test/use-swr-key.test.tsx

Currently `useSWR([1, 2, 3], fetcher)` will use the fetcher signature `fetcher(a, b, c) => data`. With this PR it changes to `fetcher([a, b, c]) => data`, which makes the argument consistent, and unblocks other features we want to add in the future. 
This also simplifies the type definitions and inference a lot.
Planned as a breaking change in 2.0.

breaking: Change the fetcher argument to be consistent with the passed key

---

src/utils/config-context.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210#discussion_r846261799
In `@types/react` 18, they remove `children` type in `FC` by default

type: fix type error on SWRConfig

---

infinite/index.ts
package.json
src/types.ts
src/use-swr.ts
test/use-swr-cache.test.tsx
test/use-swr-loading.test.tsx

After putting some time into #1922, I got the conclusion that:
- The fallback logic should be inside the useSWR hook, and middleware should receive the same _final value_ as the end user.
- To correctly implement some logic, not limiting to laggy, both middleware and the user should be able to tell if the fallback is returned.
And in 2.0, fallback will be an important feature for SWR as it covers all the SSR cases (Suspense in SSR too). It's critical to make it more complete.

Add isFallback state

---

mutation/index.ts
package.json
yarn.lock

Fixes #1923 
rollup default auto `output.exports` detection decide to output mutation as `module.exports` which is different from other subpath imports, I sticked the config to named exports in bunchee
also export the `SWRMutationHook` type

build: output mutation cjs bundle with named exports

---

infinite/index.ts
src/types.ts
src/use-swr.ts
src/utils/env.ts
src/utils/helper.ts
src/utils/web-preset.ts
test/use-swr-cache.test.tsx
test/use-swr-loading.test.tsx

This PR removes the `isFallback` state added in #1925, with a new `isLoading` state which covers more common use cases. Basically it's considered as "loading" when there is no **loaded data*** for the current key yet, while we are loading new data.
_*loaded data = data returned by the fetcher, not fallback or laggy data._
Here is a diagram showing the difference between `isLoading` and `isValidating`:

Add `isLoading` state and refactor the core

---

src/types.ts
src/use-swr.ts
test/use-swr-laggy.test.tsx

Closes #192. Unlike the [middleware solution](https://swr.vercel.app/docs/middleware#keep-previous-result), this built-in solution:
- Supports toggling the `keepPreviousData` option. 
- Handles fallback states correctly.

Add `keepPreviousData` option

---

src/use-swr.ts
src/utils/env.ts

Close #1841, close #1832. 
More discussions can be found [here](https://github.com/vercel/swr/issues/1906). In short, libraries like SWR should not support fetching data on the server side as of today.

breaking: Throw error when using suspense on the server side without fallback in React 18

---

src/types.ts
src/utils/use-swr-config.ts
test/type/config.ts

type: extends useConfig cache interface

---

src/use-swr.ts
src/utils/broadcast-state.ts
src/utils/env.ts

https://github.com/reactwg/react-18/discussions/82
18 example
https://codesandbox.io/s/adoring-ramanujan-kpe2i4?file=/src/App.tsx

remove mount check for react18

---

src/types.ts
src/use-swr.ts
src/utils/cache.ts
src/utils/mutate.ts
src/utils/use-swr-config.ts
test/type/config.ts

With the [2.0.0 update](https://github.com/vercel/swr/releases/tag/2.0.0-beta.0) (https://github.com/vercel/swr/pull/1863), each value in `cache` now holds the current states.
- Reuse the existing `State` type whenever necessary
- Remove `null` from a list of possible values of the cache
- Update the type of `createCacheHelper` to be compatible with `infinite/index.ts`
- Update the default type argument of `useSWRConfig`.
- Update the type of `MutatorOptions[`populateCache`] to allow `undefined` for `currentData` on function argument.
- `use-swr.ts`: `isLoading` was not being copied over in `onStateUpdate`. This became obvious as I saw that the `State` type contained `isLoading`.

Fix cache types

---

core/use-swr.ts
infinite/index.ts

useESE 1.1.0 is missing `exports` field which will break esm module resolution
* add extension
* `./shim/with-selector` and `./with-selector` references the same file

build: import with-selector with extension from useESE

---

package.json
tsconfig.json

This PR moves the type tests from pre-commit to tests and only leave basic type checking there, also enables `--incremental` of TypeScript to make local development faster.
Previously a commit takes 10+ seconds and now it takes ~1s.

chore: Faster type checking

---

core/use-swr.ts

Currently, the codesanbox ci is borken.

fix: try fix codesanbox ci import error

---

_internal/utils/mutate.ts
package.json
test/use-swr-local-mutation.test.tsx

Fix race conditions related to optimistic UI

---

test/type/mutator.ts
test/use-swr-local-mutation.test.tsx

This PR adds test cases for two scenarios mentioned in #1964. For the typing problem, I currently marked it as `FIXME` and it's yet to be fixed:
```ts
// FIXME: this should work.
// mutate(async () => 1, { populateCache: false })
```

chore: Add test cases for mutate

---

_internal/utils/mutate.ts
mutation/index.ts
test/use-swr-local-mutation.test.tsx

This PR fixes two case (race condition; populateCache = false) where the optimistic data isn't cleared afterwards.

fix: Should always reset to the original data after mutating with optimistic data

---

core/use-swr.ts

close #1974
https://codesandbox.io/s/loading-nh4jtc

fix: should only update cache when actually start new request

---

.codesandbox/ci.json
.github/workflows/test.yml
package.json

We're using pnpm 7, and pnpm v6 will generate different lock files. Add engine field to package.json for pnpm version checking

chore: add engine field to limit pnpm version

---

examples/autocomplete-suggestions/package.json
examples/autocomplete-suggestions/pages/index.js

Resolves: https://github.com/vercel/swr/issues/1998
Using typical implementation with `debounce` function from `lodash` package.

fix: Adding debounce for autocomplete-suggestions example

---

core/use-swr.ts
infinite/index.ts
test/use-swr-cache.test.tsx
test/use-swr-config.test.tsx

`SWRConfig.default` was introduced for accessing default value, though `default` is kinda confused property that could be default of anything or like the `default` property of an ES module.
Now rename it to `SWRConfig.defaultValue`, and document in the swr v2 docs later

BREAKING: rename SWRConfig.default to SWRConfig.defaultValue

---

_internal/utils/preload.ts
test/use-swr-preload.test.tsx

In a real-world application, a “preload” action might be initiated from multiple different places and levels (global, inside component, inside hooks, inside event callbacks). Hence deduplication is also needed here.
This improves use cases such as:
```jsx
<button onHover={() => preload('/api/user?id=' + userId, fetcher)}>
```
Where you can hover the button multiple times. Also:
```jsx
function App({ userId }) {
useEffect(() => {
preload('/api/user?id=' + userId, fetcher)
}, [userId])
...
}
```
Where there can be multiple `<App/>` elements.

fix: Avoid preloading the resource multiple times

---

core/use-swr.ts
test/use-swr-loading.test.tsx

fix #2030
https://codesandbox.io/s/swr-2030-fm0g36

fix: isLoading and isValidating should always respect cache value

---

.github/workflows/test.yml
.gitignore
core/use-swr.ts
immutable/index.ts
infinite/index.ts
mutation/index.ts
package.json
test/tsconfig.json
test/type/config.tsx

Fix ts type generation

---

_internal/types.ts
_internal/utils/cache.ts
_internal/utils/helper.ts
_internal/utils/mutate.ts
core/use-swr.ts
infinite/index.ts
infinite/types.ts
test/type/mutator.ts
test/use-swr-cache.test.tsx
test/use-swr-context-config.test.tsx
test/use-swr-infinite.test.tsx
test/use-swr-integration.test.tsx
test/use-swr-local-mutation.test.tsx
tsconfig.json

Closes #1946.
The global `mutate` API (imported directly from SWR or returned by `useSWRConfig`) can now accept a filter function, to match multiple keys for mutating:
```js
await mutate(
key => typeof key === 'string' && key.startsWith('/api/'),
undefined, // newData | (data => newData)
false,     // shouldRevalidate = true
)
```
- This deprecates the use case of accepting a function that returns a key.
- The `Cache` interface now requires a `keys()` method that returns all keys in the cache object, similar to the JavaScript `Map` instances.
(See #1946)

feat: mutate filter

---

_internal/types.ts
_internal/utils/use-swr-config.ts
test/type/config.tsx

revert #1938 
After new mutate API is landed, we're able to clear the cache or partially set cache with it, like `mutate((key) => filter(key), data)`. We encourage users to use `mutate` API instead of manipulate cache provider itself directly. 
Previously users are struggling with typing with cache provider, and trying to call `cache.clear()`, which might result into inconsistence between cache provider and react state in swr. So we introduce the new mutate API to let users manipulate cache easily. The type generics for `useSWRConfig<CacheType>` is a bit redudant if you really want to forcedly type a returned cache from context. You can just use `as` type guard like below:
```ts
const cache = useSWRConfig().cache as CustomCache
```
By default the cache type is `Cache<any>`

Revert swr config generic

---

_internal/package.json
core/package.json
immutable/package.json
infinite/package.json
mutation/package.json

Closes #2081 
Those subfolder package.json are created for providing module resolving for some bundler doesn't support `exports` field but need to resolve proper cjs or esm bundle. `"name"` and `"version"` fields are affecting webpack-license-plugin to extract the correct license, this PR will remove them before we deprecate those subfolder package.json to embrace the `exports` sugar

Remove unused info from dummy package.json

---

package.json

According to [exports sugar usage](https://nodejs.org/api/packages.html#exports-sugar)
> "types" - can be used by typing systems to resolve the typing file for the given export. This condition should always be included first.
Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.
This PR adjust the type exports to the top matched conditions to fit usage with typing

Reorder exports conditions

---

.github/workflows/test.yml
package.json
pnpm-lock.yaml

* Bump typescript to 4.8.2
* Simplify pnpm script, add `run-all-checks` for testing everything all together at once. 
* Remove single `watch/*` and `build/*`since they can be done through pnpm filter, and they're annoying when adding new export entry points

Bump typescript and assemble pnpm scripts

---

test/use-swr-preload.test.tsx

This adds a test for the `preload` API in effects, which @huozhi mentioned in https://github.com/vercel/swr-site/pull/336#discussion_r958432267.

test: add a test for preload API in effects

---

test/use-swr-loading.test.tsx

This PR adds more tests for `isLoading`.

test: add more isLoading tests for the case a key is null or an error

---

.github/workflows/test.yml

* use action/setup-node built-in pnpm cache to simplify test.yml
* use node16 for ci

ci: use action/setup-node built-in pnpm cache and bump to node16

---

test/use-swr-integration.test.tsx

This adds tests for the dependency collection behavior, which is described in the docs.
https://swr.vercel.app/docs/advanced/performance#dependency-collection
I'm working on updating the docs, so I'd like to add this to guarantee the behavior by tests.

test: add tests for dependency collection

---

_internal/utils/config-context.ts
test/use-swr-context-config.test.tsx

every time `<SWRConfig>` renders it propagates a context change even if the config did not change functionally. This can break hydration of Suspense boundaries when this component re-renders shortly after initial render which is common when there are mount effects for root level components.
This PR adds memoization so the config only changes if it's reactive dependencies change

memoize config values to avoid frequent context propagation

---

.github/workflows/test.yml
_internal/package.json
core/package.json
immutable/package.json
infinite/package.json
mutation/package.json
package.json
pnpm-lock.yaml

`bunchee@2.1.x` can bundle the types into 1 file now, which simplifies a lot. No more bunche of types are generated based on the source file paths. So now we can use a simple reference to it in exports mapping

Bundle types into one file

---

.husky/pre-commit
package.json

Seeing error `Can't find Husky, skipping post-checkout hook` when you commit.
Fix it by adding the `.husky` precommit and remove the legacy config in package.json according to the new tutorial in husky

chore: fix missing husky warning

---

_internal/utils/mutate.ts
tsconfig.json

Closes #2180 
Added the `downlevelIteration` flag when implementing the mutation filter. But swc compiles it to array-like traversal when target is es5. So we remove the flag from tsconfig.json now and then manually iterate the map iterator returning from `map.keys()`

Remove downlevelIteration and traverse iterator manually

---

core/use-swr.ts
test/use-swr-laggy.test.tsx

Fixes #2128
This fixes an issue that happens when `keepPreviousData` is enabled and the returned data and the fallback data is the same.
In this case, we have to check the laggy data, not only the fallback data, to update returned data from laggy data to the latest data. Currently, an update is ignored if the latest data and the fallback are the same.

fix: re-render when returned data and fallbackData is the same and keepPreviousData is enabled

---

_internal/types.ts
_internal/utils/mutate.ts
mutation/index.ts
test/use-swr-local-mutation.test.tsx
test/use-swr-remote-mutation.test.tsx

Errors from mutations should be separated from direct fetches. Currently, the returned and shared `error` state from `useSWR` will be mutated by `mutate` calls:
```js
const { error } = useSWR('/api')
mutate('/api', mutator) → this might update `error` if it fails
```
The main use case for that is to have a global and declarative error indicator for mutations, but then it conflicts with fetching errors (e.g. resource fails to load). With the new `useSWRMutation` hook, that is no longer needed because we can have a cleaner representation for both:
```js
const { error: loadError } = useSWR('/api')
const { error: actionError } = useSWRMutation('/api')
```
And they will be separated and scoped to different places:
For example (1) and (2) will always share the same data and error. So if the …

breaking: Change the error broadcasting behavior in mutations and add `throwOnError` option

---

_internal/types.ts
core/use-swr.ts
mutation/index.ts
mutation/types.ts

It will show the basic docs and links for this new hook when the editor supports JSDoc:

docs: Add JSDoc comments to useSWRMutation

---

mutation/index.ts

Hi!
I want to use `MutationFetcher` type.
The following workaround worked in beta.6 .
```ts
import type { MutationFetcher } from 'swr/mutation/dist/mutation/types'
```
However, now it is no longer available due to #2150 .
Or do you know of any workarounds?
example
```ts
type Key = 'ARTICLE_ID'
const likeMutation: MutationFetcher<boolean, {}, Key> = async (key) => {
const res = await fetch(`/like/${key}`, { method: 'POST' });
const json = await res.json();
return json.like;
}
const useLike = (articleId: string) => {
const res = useSWR(articleId, ...);
const mut = useSWRMutation(articleId, like);
...
}
```

type: export MutationFetcher

---

_internal/types.ts
_internal/utils/mutate.ts
test/use-swr-local-mutation.test.tsx

Resolves #2093
Support both boolean value and functional value for `rollbackOnError` for mutate options. This will let users to control rollback on error behavior based on specific error
```js
const newData = createNewData(...)
mutate(key, updateFn(newData), {
populateCache: true,
optimisticData: newData,
rollbackOnError(error) {
if (error.name === "TimeOutError") {
return true
}
return false
},
})
```

feat: support functional rollbackOnError

---

_internal/package.json
_internal/utils/helper.ts
core/package.json
core/use-swr.ts
immutable/package.json
infinite/package.json
mutation/package.json
package.json
tsconfig.json

For most use cases of SWR, users either have a modern browser (e.g. using modules in the browser + CDN), or have a bundler (esbuild, Webpack). If you still need to target old browsers, it's easy to target a lower version with the bundler.
This change makes sense for the 2.0 version. For the majority this improves the performance of SWR by a lot. According to #2095, the new bundle size will be ~80% of the `es5` target. And measured by the [SSR benchmark](https://github.com/pwrdrvr/swr-server-side), switching from `Object.assign` to the native spread operator makes SSR 4.7x faster (P50) in Node.js 16. This scales linearly with the app size, because each `useSWR()` call contains around 3 `Object.assign` operations.

Update build target to es2018

---

_internal/utils/resolve-args.ts
test/use-swr-middlewares.test.tsx

Fixes #2217
`null` is a valid type of `fetcher` argument, but the `null` fetcher becomes `undefined` in middleware. This is an unexpected behavior for middleware authors, so I've fixed it.

fix: pass null fetcher to middleware

---

_internal/types.ts
core/use-swr.ts
test/type/config.tsx

Make `FullConfiguration` as generic for better type inference. With this change, `fallbackData` from config could be inferred as `Data | undefined` instead of just `any` inside useSWR hook

types: make FullConfiguration generic

---

_internal/types.ts
core/use-swr.ts
test/type/.eslintrc
test/type/config.tsx
test/type/helper-types.tsx

Resolves #1410
When `fallbackData` is specified for the swr hook, then:
* it should match the `Data` type returning from `Fetcher`
* swr hook should always return a fulfilled `data`
* the `isLoading` always should be `false`
When `suspense` is specified for the swr hook, then:
* swr hook should always return a fulfilled `data`
* the `isLoading` always should be `false`

types: conditional swr response

---

package.json

fixes #2308
This fixes the path for the properties of the type in `package.json`.
Each `types` of `package.json` are pointed correctly.
- https://github.com/vercel/swr/blob/main/immutable/package.json#L4
- https://github.com/vercel/swr/blob/main/infinite/package.json#L4
- https://github.com/vercel/swr/blob/main/mutation/package.json#L4

fix: types properites in exports fields

---

.github/workflows/test.yml
package.json
pnpm-lock.yaml

This adds `publint` to validate packaging, which only runs on CI.
This is useful to avoid publishing an invalid package like https://github.com/vercel/swr/pull/2341.

ci: add publint to check packaging on CI

---

core/use-swr.ts
test/use-swr-error.test.tsx
test/use-swr-loading.test.tsx

close #2336
The reason for #2336 is that 
every time a revalidation is finished, a new swr hook will mount and trigger a new revalidation. 
`isValidating` will also cause similar problem here. 
https://codesandbox.io/s/isvalidating-infinite-render-xgwyyz

fix: delay revalidation if a key is already active and has error

---

.github/workflows/release.yml

pnpm cannot recognize the npm token for publishing
x-ref: https://github.com/vercel/swr/actions/runs/4014957543/jobs/6896111847

build: use npm for publish

---

.github/workflows/release.yml
.github/workflows/test.yml

Append auth token to npmrc 
x-ref: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file
Also add dependency for test workflow

build: dynamically add token and depend on test workflow

---

_internal/utils/cache.ts
core/use-swr.ts

Just as the title describes, the following is a place that has a such problem:

fix: parameters passed to subscribe is inconsistent with its declaration

---

_internal/utils/helper.ts
core/use-swr.ts
test/use-swr-streaming-ssr.test.tsx
test/utils.tsx

Here's a diagram explaining the problem:
First, In SSR, the `data` will always be `undefined` for any `useSWR` hook, because `useEffect` never runs during SSR. Same for streaming SSR because it's still SSR, but with some components being delayed a bit.
So, to make sure client hydration matches the SSR result, all `useSWR` hooks should return `undefined` during their hydration render. That's easy when we hydrate all things together, because the cache is always empty initially, and the hydration process will finish before any data fetching happens.
However, with streaming SSR React can partially hydrate a part of the app. In the example above, the first `useSWR` hook was hydrated first, and the second is still pending due to slow network or a suspense boundary. After the hydration of the …

fix: Ensure hydration matches the SSR result during streaming

---

_internal/constants.ts
_internal/types.ts
core/use-swr.ts
jest.config.js
test/use-swr-config-callbacks.test.tsx
test/use-swr-error.test.tsx

close #2412 which was introduced in #2338 
```tsx
function Demo() {
useSWR('/key', () => { throw new Error('error') })
useSWR('/key', () => { throw new Error('error') })
}
```
Previously, if we have two swr hook, There will be two retry task pushed into queue.  If first hook unmount, the error retry won't stop because of another task.
But after #2338, only the first mouted swr hook will schedule an error retry task using it own `revalidate` function. 
If the first hook unmount, the `revalidate` function will become **inactive** because of https://github.com/vercel/swr/blob/f7004ac37b2b06111043bb6f262f80fb4d5cc381/core/use-swr.ts#L263-L270
Instead of using local `revalidate` function for error retry, swr should always use the global event revalidator since it would be always **active**.

fix: Error retry should be handled by global revalidator instead of local revalidation function

---

_internal/utils/cache.ts

This PR closes #2357, by creating a copy of the `subscriptions[key]` array in the `setter` function for `initCache`. By doing this we avoid an intermittent bug where `subscriptions[key]` is mutated while the for-loop is running, potentially causing an out of bounce lookup.
By copying the object, mutations of the original object will not affect the `setter` function while executing. Alternatively we could lock write operation while running the read operation. Or use a different iterator method, that make it's own copy instead of a vanilla for-loop.
This is somewhat hard bug to reproduce, as it's highly intermittent.

fix: ensure initCache setter function stays within bounds of subscriptions

---

.github/workflows/install/action.yml

Previously, we did not setup registry-url, so `setup-node` would not craete a `.npmrc` file.
https://github.com/actions/setup-node/blob/main/src/main.ts#L58-L60
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

ci: fix publish workflow

---

_internal/types.ts
_internal/utils/cache.ts
test/type/config.tsx

close https://github.com/vercel/swr/issues/2396

Fix: type support for suspense and fallbackData(#2396)

---

infinite/index.ts
infinite/types.ts
test/use-swr-infinite.test.tsx

This PR adds the `parallel` option into `useSWRInfinite` to make revalidations in parallel.
```jsx
useSWRInfinite(getKey, fetcher, { parallel: true })
```
The default value is `false`.
When I revalidate multiple pages with `useSWRInfinite`, `useSWRInfinte` sends the revalidation requests sequentially, which is slow when we have many pages to revalidate. This especially becomes a problem when revalidations happen frequently.
```
// without parallel
page1 ====> page2 ====> page3 ====> done
// parallel
page1
page2 ====> done 
page3
```
The `parallel` option doesn't work with cursor-based APIs because cursor-based APIs send the next request based on the cursor value returned from the current request.
https://swr.vercel.app/docs/pagination#example-2-cursor-or-offset-based-paginated-api
With …

feat: add the parallel option in useSWRInfinite

---

subscription/index.ts

x-ref: revert change of  https://github.com/vercel/swr/pull/1263/commits/7963ae833a2dfb87d32a5b2c0e65aa7c36a618a5#r1118835146

Always assume subscriptions will return sub count from current key

---

test/use-swr-laggy.test.tsx

There is no test case for `keepPreviousData` without changing `key`, so I've added it.

test: add a test for keepPreviousData without changing key

---

core/use-swr.ts
e2e/site/pages/initial-render.tsx
e2e/test/initial-render.test.ts
package.json
test/use-swr-integration.test.tsx

In the past, SWR always created new snapshots for both the server and client. 
However, i found that in cases where the cache is not updated on the client during streaming, it's safe to reuse the existing client snapshot to avoid unnecessary rerendering. 
close #2473

fix: avoid creating new snapshot if cache is not updated at client during streaming

---

infinite/index.ts
infinite/types.ts

Previously, we store all page data with `inifinite-${firstPageKey}` and individual page with `${pagekey}` into cache, and sync all page data into dataRef.  
During the revalidation or mutation, we will compare dataRef with individual page to update the result.
However, we could just compare cached data directly then we don't need to store an extra copy of page data
i also update the signature of `compareFn` for `useSWRInfinite`

refactor: remove useless dataRef, always compare cached data

---

_internal/types.ts
test/type/config.tsx

This PR resolves issue https://github.com/vercel/swr/issues/2505 by reverting PR https://github.com/vercel/swr/pull/2452, and updates the tests to better explain why this issue cannot be fixed: https://github.com/vercel/swr/issues/2396
https://github.com/vercel/swr/issues/2396 suggests that if a generic is passed to the `useSWR` hook, that the library should still infer the type of the SWRConfig passed in.  However, this isn't possible in typescript due to limitations with partial inference.  That is, typescript can either infer all generics or none at all - never some but not others.
Here's a simple example to showcase this partial inference limitation:
```ts
type Foo = <A = any, B = any, C = any>(a: A, b: B, c: C) => [A, B, C]
const foo: Foo = (a, b, c) => [a, b, c]
const bar1 = foo(1, …
```

fix: swr infers incorrect `data` type for default `SWRConfig` generic type

---

test/type/config.tsx

This adds a test for types with an empty SWRConfig. refs. #2520

test: add typing test for empty config

---

test/type/trigger.ts

This TypeScript code defining a type alias Equal<A, B>. The type alias compares two types A and B and returns a boolean value indicating whether they are equal or not.
The implementation uses a conditional type with two nested conditional type expressions. However, there is a syntax error in the implementation. The find issue text is not a valid TypeScript syntax, and it causes a syntax error.

test: fix syntax error in Equal type alias implementation

---

subscription/index.ts
test/type/fetcher.ts
test/type/sub.ts

This pr intend to improve `useSWRSubscription` types.
close #2523  
* inline subscription function
```tsx
import useSWRSubscription from 'swr/subscription'
import type { SWRSubNext } from 'swr/subscription'
const useExample = () => {
const { data, error } = useSWRSubscription('key', 
(key, { next }: SWRSubNext<string, Error>)) => {
//^ key will be inferred as `key`
//....
})
return {
data,
//^ data will be inferred as `string | undefined`
error
//^ error will be inferred as `Error | undefined`
}
}
```
* declare subscription function
```tsx
import useSWRSubscription from 'swr/subscription'
import type { SWRSubscription } from 'swr/subscription'
// The first generic is Key
// The second generic is Data
// The Third generic is Error
const sub: SWRSubscription<string, string, Error> = (key, { …
```

types: improve `useSWRSubscription` types

---

examples/axios-typescript/libs/useRequest.ts
examples/axios/libs/useRequest.js

close #2541
https://swr.vercel.app/docs/arguments#passing-objects

Examples: fix type in axios-typescript example

---

subscription/index.ts
subscription/types.ts

https://github.com/vercel/swr/blob/af90b110bd1d5cbf67b97091840e14925229a722/subscription/index.ts#L60
Current implementation has already supported this kind of usage.  So i add typescript support for this.
I will also update the docs and example later.

types: allow passing function as `Data` for `useSWRSubscriptionOptions`

---

examples/api-hooks/pages/[user]/[repo].js
examples/api-hooks/pages/index.js
examples/axios-typescript/pages/[user]/[repo].tsx
examples/axios-typescript/pages/index.tsx
examples/axios/pages/[user]/[repo].js
examples/axios/pages/index.js
examples/basic-typescript/pages/[user]/[repo].tsx
examples/basic-typescript/pages/index.tsx
examples/basic/pages/[user]/[repo].js
examples/basic/pages/index.js
examples/global-fetcher/pages/[user]/[repo].js
examples/global-fetcher/pages/index.js
examples/prefetch-preload/pages/[user]/[repo].js
examples/prefetch-preload/pages/index.js
examples/server-render/pages/[pokemon].js
examples/server-render/pages/index.js
examples/suspense/pages/[user]/[repo].js
examples/suspense/pages/index.js

Removing all `a` tag from `link` tags as they are no longer supported in nextjs@13: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor

examples: fix invalid links

---

core/use-swr.ts
immutable/index.ts
infinite/index.ts
mutation/index.ts

NOTE: This is NOT to add or change API or exports and all changes is about code styling that should not effect actual behavior
The changes let tsc emit types with the hook function name not `_default` so we can auto-import by that function name (even default exported).
Now:
```.d.ts
declare const _default: SWRHook;
export { SWRConfig, _default as default, unstable_serialize };
```
With the changes:
```.d.ts
declare const useSWR: SWRHook;
export { SWRConfig, useSWR as default, unstable_serialize };
```
Also, this is done in [`useSWRSubscription`](https://github.com/vercel/swr/blob/9371f1d0632fe7d9c7ce65608cf1c1119cca01fd/subscription/index.ts#L124-L129) and [its types](https://unpkg.com/browse/swr@2.1.3/subscription/dist/index.d.ts) is exporting `useSWRSubscription as default`. So we can …

types: Allow auto-import by improving generated types

---

_internal/utils/preload.ts
core/use-swr.ts
test/type/preload.ts
test/use-swr-preload.test.tsx

Fixed `preload()` to accept the kay function similar to the `useSWR` hook, also improves the types.
The 'preload' function currently passes the fetcher function the key that was used to call it. For example, calling `preload(() => 'key', args => console.log(args))` wil show `() => 'key'`.
These changes may impact someone who have encountered this bug and worked around it like `args()` in the fetcher function. However, with the improved types, it could be detected as an error in TypeScript.

fix: pass serialized args to preload fetcher

---

package.json
pnpm-lock.yaml
test/use-swr-key.test.tsx

This PR updates `@testing-library/react` to v14.
In this PR, I've also removed an assertion that seems to be incorrect.
https://github.com/vercel/swr/commit/d95428ca65a556e3e31ae301ea09450928ea1c4d
I think SWR always calls the `key` function even if the identity is the same. The test was passed because it was asserted before re-rendering caused by an update by `updateId('first')`.

deps: update @testing-library/react to v14

---

core/use-swr.ts
examples/basic/pages/index.js
package.json
pnpm-lock.yaml
test/use-swr-integration.test.tsx
test/use-swr-refresh.test.tsx

Fixes #2446. CC @promer94.
The overall idea of `useSES` is that state changes are triggered from the external. It works in a pipeline of "external state change → compare it with local state's snapshot → trigger re-render and update local state". The main catch here is that SWR's dependency tracking system (`stateDependencies.data = true`) isn't considered as a state in that loop. But then, even if we put `stateDependencies` part of the state and compare/update it through `useSES`, we can't do a synchronous read of the snapshot which is required as we use a getter:
```js
get data() {
// Trigger a re-render synchronously with the updated snapshot
setCache({ stateDependencies_data: true })
return returnData
},
```
Mentally this should work (similar to [this …

fix: Fix dependency tracking and useSES bug

---

.github/workflows/test-release.yml
jest.config.build.js
package.json

#2580 only happens with build files, so it's hard to detect the bug before releasing a new version. We have some e2e tests, unfortunately, they are not failed because of the build setting.
To avoid that, I've added a new setting to run existing tests with build files.
This doesn't pass with v2.1.4.

test: add a new test setting to run tests with build files

---

.github/workflows/trigger-release.yml

Add new github action to trigger a release, this action will call git version command to add a new commit and tag, then it will trigger a release job. Once it can work, In the future we'll merge it with test_release job

build: add trigger release job

---

.github/workflows/install/action.yml

These inputs are not used within the action's steps. It's possible you meant to do:
```yaml
- name: Check out
uses: actions/checkout@v3
with:
fetch-depth: ${{ inputs.fetch-depth }}
```
But I don't see [any usages](https://github.com/search?q=repo%3Avercel%2Fswr%20workflows%2Finstall&type=code) of this action that pass any inputs.
Further, since we're not modifying fetch-depth via the input, we can also drop the redundant checkout step, since by definition we needed to have checked out the repository in the first place to call this action locally via `uses: ./.github/workflows/install`. It's not a huge deal but we're currently checking out the repository twice:
I didn't have any guesses for what `persist-credentials` was meant to do, but I dropped it since it's also unused.

ci: drop unused inputs and step

---

.github/workflows/trigger-release.yml

Fix typo on the `runs-on` machine
> Requested labels: ubuntu-latest1
Job defined at: vercel/swr/.github/workflows/trigger-release.yml@refs/heads/main
Waiting for a runner to pick up this job...
Job is cancelled before starting.

build: fix bad runner

---

.github/workflows/trigger-release.yml

[slack thred](https://vercel.slack.com/archives/C01LN7C5QR5/p1684853633599649?thread_ts=1684428058.764599&cid=C01LN7C5QR5)

ci: use gh token credentials for cloning repo

---

subscription/index.ts
test/use-swr-subscription.test.tsx

Currently `useSWRSubscription` does unsubscribe asynchronously, which may cause a problem if sub function only supports a singleton subscriber.
This pr fixed issue by removing the `setTimeout` in the cleanup function. 
@huozhi would love to hear you idea about this pr.
https://codesandbox.io/s/2646-lwv4yh
close: #2646

fix: do unsubscribe synchronously

---

.github/workflows/trigger-release.yml
package.json
pnpm-lock.yaml
scripts/bump-next-version.js

Use nodejs script to bump version properly, if we target beta release, it will only add beta.0 increase the number of beta version. It won't behave like npm prerelease to change to next minor/patch with beta version

ci: use script to bump semver version

---

core/use-swr.ts
test/use-swr-suspense.test.tsx

https://codesandbox.io/s/suspense-keeppreviousdata-4iotsh?file=/src/App.js
close #2650

fix: keepPreviousData should also work in suspense

---

_internal/src/types.ts
_internal/src/utils/mutate.ts
test/use-swr-local-mutation.test.tsx

Pass `displayedData` as second parameter to functional `optimisticData`.
To better support slow networks, one may want to use `displayedData` rather than `currentData` when using functional `optimisticData` so that several mutations can apply the optimistic updates before any is resolved and keep the UI consistent with the user actions.
https://github.com/vercel/swr/assets/3280300/c50abcd4-445d-41dd-9c53-9554e7330c55
https://github.com/vercel/swr/assets/3280300/cb9d37d1-78ab-4dbf-a8e3-03a2fb6b5842

Pass displayed data as second parameter of functional optimistic data

---

package.json
pnpm-lock.yaml

Fix `https://unpkg.com/browse/swr@2.2.0-beta.3/_internal/dist/index.d.ts` is missing most of the imports but used the react-server exports types

build: fix conflict types for index and index.react-server

---

core/src/index.ts
immutable/src/index.ts
infinite/src/index.ts
mutation/src/index.ts
package.json
pnpm-lock.yaml
subscription/src/index.ts

Upgrade bundler (where it supports preserving the "use client" directive now) and add `"use client"` for the all API except `react-server` exports
Addressing few RSC related discussion, since we've already provided the `react-server` exports condition for server components now we can add `"use client"` directive to the API which only should be used in client components
Related to #2221
Rsolves #2292
Closes #2464

Add use client directive for client components exports

---

core/package.json
core/src/env.d.ts
core/src/index.ts
immutable/src/index.ts
infinite/src/index.ts
mutation/src/index.ts
package.json
pnpm-lock.yaml
subscription/src/index.ts

According to [docs](https://react.dev/reference/react/use-client), `SWRConfig` should not be directly used in React Server Components since it has lots of non-serializable props. So we remove the 'use client' directive and add client-only to `useSWR` entry  in this pr.

remove the 'use client' directive and add client-only to useSWR entry.

---

_internal/src/constants.ts
_internal/src/events.ts
_internal/src/index.react-server.ts
_internal/src/index.ts
_internal/src/types.ts
_internal/src/utils/cache.ts
_internal/src/utils/mutate.ts
_internal/src/utils/preload.ts
infinite/src/index.ts
infinite/src/serialize.ts
test/use-swr-infinite-preload.test.tsx

This PR fixes the use-case where I want to preload the first page of data from useSWRInfinite using the `preload` function from `swr`. 
The issue was that `useSWRInfinite` prefixes the cache key's internally.  Adding additional logic to the preload `middleware` function to handle the condition where the key starts with INFINITE_PREFIX as the consumer calling `preload` does not know about the prefix.

fix(infinite): Fix the ability to use preload along with useSWRInfinite

---

_internal/src/utils/mutate.ts
test/use-swr-remote-mutation.test.tsx

E.g.:
```
req------------->res
mutate------->end
```
In this case, the res would be ignored while req would not be triggered a revalidation.

Fix the issue that useSWR revalidation isn't triggered if the useSWR call happens after mutation

---

_internal/src/types.ts
_internal/src/utils/cache.ts
_internal/src/utils/config.ts
_internal/src/utils/mutate.ts
core/src/use-swr.ts
infinite/src/index.ts
mutation/src/types.ts
subscription/src/types.ts
test/type/mutate.ts
test/use-swr-infinite.test.tsx
test/use-swr-local-mutation.test.tsx

Fix for [issue 2690](https://github.com/vercel/swr/issues/2690) [issue 2647](https://github.com/vercel/swr/issues/2647) and [issue 2661](https://github.com/vercel/swr/issues/2661)
1. Make mutate/trigger always return the result of fetcher
2. Make KeyedMutator/ScopedMutator accept generic type parameters to make the data type flexible and work with populateCache

fix(mutate): fix types of mutate/trigger; make mutate/trigger always return the result of fetcher

---

README.md
core/src/use-swr.ts

Hello,
I was going to use swr and when I was looking at the github readme I've noticed that the loading state was handled by `!data`. However on the swr docs main page https://swr.vercel.app/ overview example has the `isLoading` value.
I thought that it would be nice to have this readme example consistent with website.

docs: use isLoading instead of !data

---

mutation/src/state.ts

It should use startTransition only when IS_REACT_LEGACY is false

fix: It should use startTransition only when IS_REACT_LEGACY is false

---

_internal/src/types.ts

this was already redundant but it will actually cause problems with TS 5.3 (in the future), see: https://github.com/microsoft/TypeScript/pull/55229#issuecomment-1694383442

fix: simplify `ArgumentsTuple`

---

_internal/src/types.ts
test/type/fetcher.ts

Resolve #2758 by remove permissive type. Because BaseFetcher allows `(...args: any)` when your key and fetcher key mismatch you fall through to the override:
```
<Data = any, Error = any>(
key: Key,
fetcher: BareFetcher<Data> | null
): SWRResponse<Data, Error>
```
This should instead be flagged by typescript. Removing that override broke some tests added in #1640 which appeared to be designed to allow for backwards compatible hooks that don't conform to `StrictKey` to be compatible. Specifically these two type tests:
```
useSWR<{ id: number }>('/api/', () => ({ id: 123 }))
useSWR<string, any>('/api/', (key: string) => key)
```
The new override covers these while retaining type inference by just not defaulting to `StrictKey` which appears to be the main issue.

fix: remove permissive type

---

core/src/use-swr.ts
infinite/src/index.ts

This PR fixed #2402
According to [this document](https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web), React Native-specific code can use the '.native.js' suffix, while standard React web code uses the '.js' suffix.  By removing `index.js` suffix of `use-sync-external-store/shim`, bundling tools like Metro/Webpack could choose the right file for each platform.
I haven't tested this PR on React Native because I'm not familiar with React Native development and I have no idea how to downgrade React to 17. However, I can reproduce the issue and test the PR on [GojiJS](https://github.com/airbnb/goji-js),  which is a React-like framework based on `react-reconciler` and shares many technical specifications with React Native, …

Remove `index.js` suffix of `use-sync-external-store/shim` to support React Native

---

_internal/src/types.ts
infinite/src/index.ts
test/type/mutate.ts
test/use-swr-local-mutation.test.tsx

Closes #2744 
Hi,
as a few other also noticed the typings used in the bound mutator do not default anymore to the data type used in `useSWR<ThisOne>` and needs to be specified explicitly everytime right now.
Looking at the other types surrounding the `KeyedMutator` type it seems reasonable to default to the data type specified at `useSWR<...>`, e.g. as done here:
https://github.com/vercel/swr/blob/e510955d42b472c8d45034c51b8acc12980aa2e7/_internal/src/types.ts#L372-L381
Let me know if and where a test could be added if you want to test the typings.
Thanks, Vincent

fix: default to fetch type in keyed mutator

---

core/src/use-swr.ts
infinite/src/index.ts

Removing `/index.js` broke module resolving for `use-sync-external-store/shim`
Reverts vercel/swr#2767
x-ref: #2801

Revert "Remove `index.js` suffix of `use-sync-external-store/shim` to support React Native"

---

test/use-swr-local-mutation.test.tsx

Currently, we see act warnings when running unit tests. This PR fixes all warnings.
<details>
<summary>act warnings log</summary>
```
pnpm test -- --verbose 
> jest "--verbose"
console.error
Warning: An update to Page inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at Page (/test/use-swr-local-mutation.test.tsx:556:17)
at value (/_internal/src/utils/config-context.ts:33:11)
at children (/test/utils.tsx:35:28)
245 |           key,
246 |           (current: State<Data, any>, prev: State<Data, any>) …
```

fix: all act warnings

---

.github/workflows/test-canary.yml
.github/workflows/test-release.yml

Now we run `pnpm test:build`, which uses build files for testing, and this PR also adds `pnpm test` on CI to catch mistakes for settings.

test: run pnpm test on CI

---

src/core/use-swr.ts

fix: allow onErrorRetry on inactive tab without focus/reconnect revalidation

---

src/_internal/types.ts
src/_internal/utils/mutate.ts
src/infinite/index.ts
src/infinite/types.ts
src/mutation/types.ts
test/use-swr-infinite.test.tsx
test/use-swr-local-mutation.test.tsx
test/use-swr-remote-mutation.test.tsx

This PR proposes to allow us to pass a function to the `revalidate` option.
My main motivation is to provide a way to revalidate specific pages with `useSWRInfinite`. See more details in the section below.
refs. https://github.com/vercel/swr/issues/1590#issuecomment-1000447513, https://github.com/vercel/swr/discussions/616#discussioncomment-81971
This also allows us a conditional revalidation based on the result of the mutation.
I can implement this feature as a separate option, but I think having `revalidate` and `revalidatePage` (?) is confusing. This proposal only adds a way to pass a function to the `revalidate` option, but this gives us more capabilities.
```diff
- revalidate?: boolean
+ revalidate?: boolean | (data: Data, key: Arguments) => boolean
```
`data` is the latest data, …

feat: pass a function to the revalidate option in mutate

---

package.json
src/_internal/types.ts
src/_internal/utils/config-context.ts
test/type/config.tsx

Fixes the type mismatch in `SWRConfiguration` with the non-exported internal `Config` type with the FC `SWRConfig` export. This was causing the following issues:
- Custom configs could not be typed with `:SWRConfiguration`
- The internal `Config` type was used but not exposted
- Aligns the documentation with `TypeScript` section and `react-native` section, as combining these two approaches produce a type error right now.
- Closes #2881

fix: SWRConfiguration type

---

.github/workflows/test-canary.yml
.github/workflows/test-legacy-react.yml
jest.config.js
package.json
src/_internal/utils/env.ts
test/use-swr-legacy-react.test.tsx
test/use-swr-server.test.tsx
test/utils.tsx

Follow up of #2903 
- Use separate test job to coverage legacy react build (react 17)
- Ignore env.ts since it's not necessary to be covered

chore: simplify test coverage strategy

---

env.d.ts
package.json
pnpm-lock.yaml
src/core/index.ts

Since we've already have `react-server` condition, `client-only` doesn't help much as we're always picking up `react-server` condition in RSC bundling layer, default condition is always bundled into client layers

Drop client-only

---

src/_internal/utils/env.ts

The `window` object became deprecated in Deno (https://github.com/denoland/deno/pull/22057). Instead, they recommend us to use `globalThis` or `self`. For the change, I also referred to here (https://deno.land/x/udibo_react_app@0.3.3/env.ts?source=#L7)

fix: Replace the deprecated 'window' with 'globalThis' for Deno

---

.github/workflows/test-canary.yml
test/use-swr-promise.test.tsx
test/use-swr-subscription.test.tsx
test/use-swr-suspense.test.tsx

Those checks could be safely removed since it's just implementation detail.

test: remove console.error times check

---

e2e/site/app/suspense-fallback/layout.tsx
e2e/site/app/suspense-fallback/promise/page.tsx
e2e/site/next.config.js
e2e/site/package.json
e2e/test/suspense-fallback.test.ts
package.json
pnpm-lock.yaml
src/_internal/index.react-server.ts
src/index/config.ts
src/index/index.react-server.ts

Last beta release breaks `SWRConfig` on the server layer. If you `import { SWRConfig } from "swr"` inside a Server Component, it will go through these import paths infinitely:
> `swr/dist/core/react-server.mjs`
> `export { SWRConfig } from 'swr/_internal';`
> `swr/dist/_internal/react-server.mjs`
> `export { SWRConfig } from 'swr/_internal';`
> repeat…
Reverting swr config to previous change and add an e2e test for it

Fix bundling of client entry chunks 

---

.github/workflows/install/action.yml
.github/workflows/test-canary.yml
.github/workflows/test-legacy-react.yml
.github/workflows/test-release.yml
.github/workflows/trigger-release.yml
package.json
pnpm-lock.yaml
test/use-swr-infinite-preload.test.tsx

The failed test is skiped because our current implmentation of useSWRInfinite with suspense is not robust enough. 
https://github.com/vercel/swr/blob/6da84a375f59ec88b7dc0eedc27ed8ab1e56066a/src/infinite/index.ts#L138
The internal swr hooks inside `useSWRInfinite` could never be preload properly to avoid unnecessary loading with current api design.

ci: fix ci error and upgrade action version

---

src/infinite/index.ts

When using `"moduleResolution": "Bundler"` in tsconfig.json for a TypeScript project, and implicitly referencing `SWRInfiniteMutatorOptions` you get this error:
```bash
Exported variable '<redacted>' has or is using name 'SWRInfiniteMutatorOptions' from external module "/path/node_modules/swr/dist/infinite/index" but cannot be named.ts(4023)
```
These errors can be resolved by explicitly exporting these implicitly references types from `swr`.

Add SWRInfiniteMutatorOptions type to export

---

test/use-swr-infinite.test.tsx

This test is misleading so I've updated it. In this case, we should pass the current data as the first argument.

test: update the revalidate function test for useSWRInfinite

---

src/core/index.ts

It would be helpful to have access to the ScopedMutator, so that API helper functions can easily specify a `useSWRConfig` `mutate` function as a parameter. For example:
```tsx
import { ScopedMutator, useSWRConfig } from 'swr';
async function myMultiStepApiTask(mutate: ScopedMutator) {
await postToKey1();
await mutate(key1);
await postToKey2();
await mutate(key2);
}
function MyMultiStepButton() {
const { mutate } = useSWRConfig();
return <button type="button" onClick={() => myMultiStepApiTask(mutate)}>Go</button>;
}
```

Export ScopedMutator type

---

src/core/use-swr.ts
test/use-swr-config.test.tsx

Check if config.fallback is undefined.
If config.fallback is undefined, don't access to config.fallback[key].
- Closes #2912

fix: check if config.fallback is undefined

---

package.json
pnpm-lock.yaml
src/_internal/utils/config.ts

Currently, we are using the `stableHash` utility (that we use for hashing resource keys) to handle the deep comparison task which is a great code reuse. However, in the worse case it might be a performance bottleneck when the payload is a large object but different from the previous data, as comparison cannot be done during the traversal.
This PR re-introduces `dequal/lite` as a dependency and uses that for comparison instead.

fix: Improve comparison performance

---

package.json
pnpm-lock.yaml
src/_internal/utils/hash.ts
test/unit/serialize.test.ts
test/unit/utils.test.tsx

This pr intends to fix the inconsistent behavoir of swr's `hash` in edge-runtime dev mode.
The reason for this problem is because we're using `node.js` to simulate the `edge-runtime`  for local development 
The global `Array` and `Object` of edge-runtime are injected from `node.js` and the JS engine does not use global Array/Object constructor while building an array/object literal.
Then in dev mode
```
[].constructor !== Array.constructor
{}.construrtor !== Object.contructor
```
So we need find alternative to determine whether a key is an array or a `plain object`

fix #3030 and run relateive test in edge-runtime

---

package.json
pnpm-lock.yaml

bump use-sync-external-store to latest which works with react 19
stack on #3049

upgrade use-sync-external-store to support react 19

---

src/mutation/index.ts
src/mutation/state.ts

This pull request aims to improve the type safety and reliability of the useStateWithDeps hook in React. Specifically, the changes address potential issues with accessing state properties using dynamic keys, ensuring that TypeScript correctly identifies and enforces the types of state properties.
Changes Implemented:
Type-Safe Iteration:
Replaced the direct for...in loop with a more type-safe iteration using Object.prototype.hasOwnProperty.call() to avoid errors related to iterating over unexpected properties.
Non-null Assertion:
Added a non-null assertion (payload[k]!) to ensure that payload[k] is not undefined when updating the state, preventing runtime issues.
Improved Type-Safe Access:
Used const k = key as keyof S to inform TypeScript that key is a valid key of S, improving the type …

Improve-Type-Safety-and-State-Access-in-useStateWithDeps-Hook

---

src/mutation/types.ts

Missing `throwOnError` in `SWRMutationHook`'s options.  Update code to let users pass option `throwOnError`.
Example:
```
useSWRMutation('/api/mutate-server-action', () => action(), { throwOnError: true })
```

fix: missing `throwOnError` in SWRMutationHook options

---

src/_internal/utils/env.ts
src/_internal/utils/helper.ts

In the new version of swr (2.3.0), `globalThis` is used to determine if the environment is Deno. (https://github.com/vercel/swr/pull/2915)
This will cause errors in lower version browser environments (android <=13) (ios <12) where globalThis does not exist.
Since swr is a widely used request library, we hope to ensure compatibility as much as possible.
In Deno 2, window has been removed, as discussed in this issue: https://github.com/denoland/deno/issues/13367
I have added a new method `isLegacyDeno` for this check. 🙏🏻

fix: sever env detection for deno

---

.github/workflows/install/action.yml

seeing failure ci job x-ref: https://github.com/vercel/swr/actions/runs/13147053165/job/36687350969?pr=4084
trying to lock pnpm version
Related corepack issue: https://github.com/nodejs/corepack/issues/612

ci: update pnpm setup and lock pnpm vesion

---

src/index/use-swr.ts

Instead of using type assertion
```
return { ... } as SWRResponse<Data, Error>;
```
Creating a new object with explicit type annotation provides better type safety
```
const swrResponse: SWRResponse<Data, Error> = { ... };
return swrResponse;
```

refactor: type improvement of `useSWRHandler`

---

src/index/use-swr.ts

Fix for https://github.com/vercel/swr/pull/4084. Only `undefined` values should be avoided. `null` is ok.

(fix) keepPreviousData: return fallback instead of undefined value

---

src/_internal/utils/cache.ts

Use `Object.create(null)` to create safe empty object used as simple map

enhance: use empty prototype object

---

src/index/use-swr.ts
test/use-swr-cache.test.tsx
test/use-swr-focus.test.tsx

Related to https://github.com/vercel/swr/issues/2856
Opened for discussion really - is there any reason we can't do this?

Initialise nextFocusRevalidatedAt on mount

---

src/_internal/utils/mutate.ts
test/use-swr-remote-mutation.test.tsx

Hello!
"if (!error)" make cast value to boolean type and if value is cast to false then the error is skipped.
Sandbox: https://codesandbox.io/p/sandbox/6s9dw7
Example:
````javascript
import useSWRMutation from "swr/mutation";
const fetcher = () => {
return new Promise((_, reject) => reject("")); // or null/undefined/false/0
};
const Component = () => {
const { trigger } = useSWRMutation("/example", fetcher);
const handleClick = () => {
trigger()
.then(() => {
console.log("skip error");
})
.catch(() => {
console.log("error");
});
};
return <button onClick={handleClick}>Execute</button>;
};
```

fix: check "if (!error)" skip error if value is cast to false

---

src/_internal/utils/hash.ts

See issue https://github.com/vercel/swr/issues/4090
This code extracts out the getting of a type name rather than repeating that 3x.
This increases performance of the hot path through the code.

fix: Performance improvement by reducing calls to toString()

---

e2e/site/app/perf/page.tsx
e2e/test/perf.test.ts
src/index/use-swr.ts

The SWR hook was experiencing performance issues due to inefficient request deduplication logic, causing unnecessary re-renders and redundant API calls when multiple components used the same key.
Added a performance optimization at line 644 that checks if a request is already in progress before initiating a new one:
```ts
// Performance optimization: if a request is already in progress for this key,
// skip the revalidation to avoid redundant work
if (!FETCH[key]) {
if (isUndefined(data) || IS_SERVER) {
// Revalidate immediately.
softRevalidate()
} else {
// Delay the revalidate if we have data to return so we won't block
// rendering.
rAF(softRevalidate)
}
}
```
- Deduplication Check: Before triggering initial revalidation, the code now checks if `FETCH[key]` exists, preventing duplicate …

fix: Optimize the revalidation logic for same key requests.

---

src/_internal/utils/use-swr-config.ts
test/use-swr-context-config.test.tsx

https://github.com/vercel/swr/issues/4093

perf: optimize `useSWRConfig` with `useMemo` to maintain stable reference

---

src/_internal/types.ts

The TSDoc for `PublicConfiguration.onDiscarded` is inconsistent with the description on the [SWR official website](https://swr.vercel.app/docs/api).
Updated TSDoc to match the [SWR official website](https://swr.vercel.app/docs/api):
- Original: `callback function when a request is ignored`
- Updated: `callback function when a request is ignored due to race conditions`
https://github.com/vercel/swr/issues/2979

doc: Sync `PublicConfiguration.onDiscarded` tsdoc with SWR official website

---

src/_internal/types.ts

Reverts vercel/swr#2947 as the types checking are failing
x-ref: https://github.com/vercel/swr/actions/runs/16391924632/job/46319031893

Revert "feat: modify cache type to allow generic usage"

---

e2e/site/app/suspense-undefined-key/page.tsx
e2e/test/suspense-undefined-key.test.ts
src/index/use-swr.ts

Related change in #4150, the error show not directly throw when key is falsy like disabled mode
Fixes #4155

fix: do not error when not enabled during suspense
