- README.md
> Add link to RFC

- src/index.ts
- src/types.ts
- src/use-swr.ts
Closes #12 
Not sure if I covered the use cases for the input values. If I missed something, let me know and I'll update it.
I also added a generic response, to provide types to the response object.
> Updating types to be more helpful

- package.json
- src/libs/reactBatchedUpdates.native.ts
- src/libs/reactBatchedUpdates.ts
- src/types.ts
- src/use-swr.ts
- test/use-swr.test.tsx
- yarn.lock
- remove `unstable_batchedUpdates`, use `useReducer` instead
- remove React Native .native module
- remove react-dom and react-native from (peer) deps 
This will also unblock #89
> Replace batchedUpdates with reducer

- README.md
- src/types.ts
- src/use-swr.ts
- test/use-swr.test.tsx
- fix #128
- use badgen.net
- allow arg array returning function as key
- allow fetcher to be undefined, fix #123
- change splice to swap (which is O(n) → O(1))
> Improvements

- .gitignore
- package.json
> Add esm build

- README.md
> Fix 'SSR with Next.js' code error

- examples/local-state-sharing/pages/index.js
Added validation false in mutate.
> local state sharing example

- package.json
- tsconfig.json
Fix #163
Change cjs build target to ES5, esm build target to ESNext
> add es5 support

- .eslintignore
> ESlint ignore add esm folder

- src/config.ts
- src/types.ts
- src/use-swr.ts
- test/use-swr.test.tsx
#147 
Sometimes it is necessary to confirm whether to change the cache based on specific fields.
Maybe add a config attribute?
> Allow use custom isEqual method

- src/use-swr.ts
Also fix unsubscribe callback assignment
Closes #301
> Use window as a target for online event

- README.md
This was implemented in #219 but wasn't documented in the readme.
> Document the compare option

- examples/api-hooks/package.json
- examples/autocomplete-suggestions/package.json
- examples/axios-typescript/package.json
- examples/axios/package.json
- examples/basic-typescript/package.json
- examples/basic/package.json
- examples/focus-revalidate/package.json
- examples/global-fetcher/package.json
- examples/local-state-sharing/package.json
- examples/optimistic-ui/package.json
- examples/pagination/package.json
- examples/prefetch-preload/package.json
- examples/refetch-interval/package.json
- examples/server-render/package.json
- examples/storage-tab-sync/package.json
- examples/suspense/package.json
Handles the upgrade notifications
> Upgrade Next.js

- src/use-swr.ts
I changed if condition to be the same as [line 376](https://github.com/zeit/swr/blob/master/src/use-swr.ts#L376) and [line 426](https://github.com/zeit/swr/blob/master/src/use-swr.ts#L426). Then I removed the 'do nothing' and made the if statement much easier.
> change if condition and remove 'do nothing'

- examples/optimistic-ui-immer/README.md
- examples/optimistic-ui-immer/libs/fetch.js
- examples/optimistic-ui-immer/package.json
- examples/optimistic-ui-immer/pages/api/data.js
- examples/optimistic-ui-immer/pages/index.js
This adds a modified version of the Optimistic UI example but using Immer to perform the mutation in a safe way ensuring we always create a new object.
> Add Optimistic UI with Immer example

- examples/axios/libs/useRequest.js
> fix axios example unexpected mutation behavior

- README.md
try to rephrase the confused section mentioned in #393 . if it's not correct, please point out my mistake I'll fix it.
> docs: update notes for returned data from mutate section

- src/use-swr.ts
- test/use-swr.test.tsx
> Fix mutate not disposing older async mutations

- src/use-swr.ts
> Fix state not updated when using spread syntax

- examples/api-hooks/README.md
- examples/autocomplete-suggestions/README.md
- examples/axios-typescript/README.md
- examples/axios/README.md
- examples/basic-typescript/README.md
- examples/basic/README.md
- examples/focus-revalidate/README.md
- examples/global-fetcher/README.md
- examples/optimistic-ui-immer/README.md
- examples/optimistic-ui/README.md
- examples/pagination/README.md
- examples/prefetch-preload/README.md
- examples/refetch-interval/README.md
- examples/server-render/README.md
- examples/storage-tab-sync/README.md
Fixes one-click deploy links (fix #416)
> Replace ZEIT with Vercel in examples

- src/use-swr.ts
> Update keyErr on the cache when mutating

- src/use-swr-infinite.ts
- test/use-swr-infinite.test.tsx
```js
useSWRInfinite(getKey, fetcher, { persistSize: true })
```
The boolean value will be `false` by default. When enabling it, the page size will not be reset to 1 (or `initialSize` if set) when the first page's key changes.
https://github.com/vercel/swr/pull/435#discussion_r443202280
> Add persistSize option to useSWRInfinite

- README.md
> Update README link 

- examples/axios-typescript/libs/useRequest.ts
fix bug https://github.com/vercel/swr/issues/238#issuecomment-633043782
> fix typescript warning

- README.md
This refers to issue #306 which was not resolved.
I have added the example and given a short description as well.
(Also done a Prettier edit for better readablility. The overall documentation flow is not affected)
> Added example for SWR Request De-duplication feature

- src/use-swr.ts
if the cache data is 0 or null, now the initialData will be from config. it is not expected
> chore: fix error when data tobe 0 null

- examples/axios-typescript/package.json
- examples/axios-typescript/pages/api/data.js
- examples/axios/package.json
- examples/axios/pages/api/data.js
Update to remove dependencies and confusion. Proper `data` objects handle through axios.
> Remove Isomorphic Fetch from Axios Typescript example

- src/types.ts
> fix: missing dedupe in updaterInterface

- README.md
**Descriptions:**
- fix readme's Request Deduplication example by editing wrong component name
- check readme at https://github.com/vercel/swr#request-deduplication
> doc: fix readme's Request Deduplication example

- src/use-swr.ts
- test/use-swr.test.tsx
> fix: error should not be cleared while revalidating

- package.json
Closes https://github.com/vercel/swr/issues/724
Let me know if you would like any other changes to accompany this one.
> Accept React 17 as a peer dependency

- src/use-swr.ts
> Replace rIC with rAF

- package.json
- src/use-swr.ts
- test/use-swr.test.tsx
merge master 0.3.8 changes into next branch
> Merge master to next branch

- jest.config.js
- test/use-swr.test.tsx
* merge first two tests into one
* replace waitForDomChange
* disbale ts-jest warning
> update test useSWR

- .eslintrc
This fixes the CI error introduced by the Deno PR.
> Fix eslint error

- examples/api-hooks/README.md
Updated the Vercel deploy link to the correct directory
> Update api-hooks example README.md

- src/use-swr.ts
fix my mistake at #638 
Repro: https://codesandbox.io/s/swr830-65m4c?file=/pages/index.js
> close #830

- test/use-swr.test.tsx
I wrote a test when porting over the default fetcher and thought I'd share it.
From: https://github.com/Kong/swrv/pull/120
> test(fetch) add test for default fetcher

- .eslintignore
- .gitignore
- CONTRIBUTING.md
- package.json
- tsconfig.json
- yarn.lock
https://user-images.githubusercontent.com/15878786/102889914-72fe8c80-4496-11eb-9636-f36067f36b0e.mov
```bash
yarn install
yarn register
yarn prepare:vite
yarn dev:vite
```
- For SSR
```bash
yarn install
yarn register
yarn prepare:next
yarn dev:next
```
> add playground for debugging using vite and next.js

- README.md
This is based on https://github.com/vercel/swr-site/pull/65 and follows up on https://github.com/vercel/swr/pull/845.
> docs: add isPaused() into the options

- src/use-swr.ts
- test/use-swr.test.tsx
Fix: #854 
https://codesandbox.io/s/stale-onsuccess-call-doice?file=/pages/index.js
> check key before calling callback

- src/use-swr-infinite.ts
- test/use-swr-infinite.test.tsx
This is diffs that is the result of `yarn format` on the master branch.
> chore: format files

- examples/infinite/README.md
- examples/infinite/libs/fetch.js
- examples/infinite/package.json
- examples/infinite/pages/index.js
This example shows how to use useSWRInfinite
> Add example using useSWRInfinite

- jest.config.js
- tsconfig.json
- tsconfig.test.json
#932 accidentally changed the esm directory structure.
> keep old esm directory structure

- src/libs/deep-equal.ts
https://codesandbox.io/s/infallible-meadow-r5v8x?file=/src/App.js
> fix dequal

- test/use-swr-error.test.tsx
This is a followup PR of #933.
I've refactored tests for errors
> test: refactor use-swr-error.test.tsx

- test/use-swr-infinite.test.tsx
- test/utils.ts
I've refactored `use-swr-infinite.test.tsx`
> test: refactor use-swr-infinite.test.tsx

- test/use-swr-integration.test.tsx
I've refactored `use-swr-integration.test.tsx`
> test: refactor use-swr-integration.test.tsx

- src/index.ts
- src/types.ts
- src/use-swr-infinite.ts
> types: expose KeyLoader

- test/use-swr-key.test.tsx
I've refactored use-swr-key.test.tsx
> test: refactor use-swr-key.test.tsx

- test/use-swr-local-mutation.test.tsx
I've refactored use-swr-local-mutation.test.tsx
> test: refactor use-swr-local-mutation.test.tsx

- test/use-swr-offline.test.tsx
I've refactored use-swr-offline.test.tsx
> test: refactor use-swr-offline.test.tsx

- test/use-swr-suspense.test.tsx
This is the last follow-up PR of #933!
I've refactored use-swr-suspense.test.tsx.
> test: refactor use-swr-suspense.test.tsx

- package.json
- yarn.lock
upgrade bunchee to 1.5.4
* less dev deps
* es5 transform all (this was a bug before, which doesn't transform all es2015 - es2020 syntaxes)
> build: upragde bundler

- src/types.ts
- src/use-swr.ts
fix #1155
https://codesandbox.io/s/mutate-generic-e3fqj?file=/src/App.tsx
> fix global mutate generic

- test/use-swr-infinite.test.tsx
> Add test case for useSWRInfinite

- src/use-swr.ts
- src/utils/cache.ts
- src/utils/config.ts
- src/utils/helper.ts
- src/utils/state.ts
- src/utils/web-preset.ts
Some tweaks to make the code more consistent and improve readability. Notable changes:
- no more `setTimeout` needed for `focusThrottleInterval`
- shared no-op function
> Code refactoring

- package.json
> Add package.json to module exports

- package.json
- yarn.lock
Fixes bunchee watch issue that doesn't update generated assets before
> update bunchee 1.6.2

- examples/infinite/pages/index.js
Per https://github.com/vercel/swr/pull/1272
> chore: update useSWRInfinite import

- src/types.ts
- src/use-swr.ts
- src/utils/config.ts
- src/utils/merge-config.ts
- test/use-swr-cache.test.tsx
- test/use-swr-config.test.tsx
- test/use-swr-infinite.test.tsx
- test/use-swr-integration.test.tsx
- test/use-swr-local-mutation.test.tsx
- test/use-swr-suspense.test.tsx
_Note: we need to update README (#656) and docs_.
> Rename fallbackValues and initialData

- src/utils/cache.ts
> fix: cache is missing on server side

- .github/workflows/test.yml
Reverts vercel/swr#1398
The auth issue blocks contributors to pass PR check
> Revert "ci: setup size bot"

- src/types.ts
closes #1386 
make return state `Readonly`
> Feature: make return state(data, error and isValidating) readonly

- src/use-swr.ts
- tsconfig.json
if there's error bunchee should stop building
> build: no emit on error

- test/use-swr-cache.test.tsx
This is a follow-up PR of #1435
> test: refactor use-swr-cache-test

- test/use-swr-context-config.test.tsx
- test/use-swr-focus.test.tsx
- test/use-swr-local-mutation.test.tsx
- test/use-swr-revalidate.test.tsx
This might be too big as a single PR 🙏
> test: refactor mutation tests

- test/use-swr-immutable.test.tsx
- test/use-swr-infinite.test.tsx
> test: refactor immutable and infinite hook tests

- test/use-swr-offline.test.tsx
- test/use-swr-refresh.test.tsx
This is the final PR of this refactoring. Thank you for your reviews!!! 🙏
> test: refactor offline and refresh tests

- examples/infinite-scroll/hooks/useOnScreen.js
> example: add ref checking condition

- package.json
- tsconfig.check.json
- tsconfig.json
`test/type` files are included in `test/tsconfig.json`. so we can run two project for both src and tests
> chore: remove duplicate configs

- package.json
- tsconfig.check.json
- tsconfig.json
https://codesandbox.io/s/type-fetcher-forked-38g6f?file=/src/App.tsx
> typing: fix-type-generation

- infinite/index.ts
- src/types.ts
- test/type/state.ts
- test/use-swr-local-mutation.test.tsx
> chore: Mark returned states and mutate callback argument as readonly

- test/unit.test.tsx
- test/use-swr-reconnect.test.tsx
This ensures that the `use-swr` core file is 100% covered by tests.
> test: Add tests for reconnect and merge-config

- infinite/index.ts
- test/use-swr-infinite.test.tsx
> fix: Allow empty mutate argument list for infinite

- src/types.ts
Finishes the work to close #1589 by add defaults for SWRResponse and lint
> Add defaults for SWRResponse

- examples/.eslintrc
- examples/api-hooks/package.json
- examples/autocomplete-suggestions/package.json
- examples/axios-typescript/package.json
- examples/axios-typescript/pages/api/data.ts
- examples/axios-typescript/tsconfig.json
- examples/axios/package.json
- examples/basic-typescript/package.json
- examples/basic-typescript/pages/api/data.ts
- examples/basic-typescript/pages/index.tsx
- examples/basic-typescript/tsconfig.json
- examples/basic/package.json
- examples/focus-revalidate/package.json
- examples/global-fetcher/package.json
- examples/infinite-scroll/package.json
- examples/infinite/package.json
- examples/local-state-sharing/package.json
- examples/optimistic-ui-immer/package.json
- examples/optimistic-ui/package.json
- examples/prefetch-preload/package.json
- examples/refetch-interval/package.json
- examples/server-render/package.json
- examples/storage-tab-sync/package.json
- examples/suspense/package.json
x-ref: https://github.com/vercel/swr/discussions/1592
* update ts example with `strict: true`
* mark next version to latest
> example: update typescript examples with strict ts mode

- test/use-swr-error.test.tsx
- test/use-swr-revalidate.test.tsx
> fix: remove unnecessary async

- src/types.ts
This overriding should be same with previous 3 ones
> types: remove duplicated typing def

- test/use-swr-infinite.test.tsx
Add a test for #1325 to ensure it will be working fine in the future.
> chore: Add test case for `getKey` in `useSWRInfinite`

- examples/local-state-sharing/package.json
> Fix local state sharing example deps

- src/utils/helper.ts
> doc: comment helper

- src/types.ts
- src/utils/with-middleware.ts
- test/use-swr-focus.test.tsx
* add delay to focus test
* middlewares -> middleware
> test: add delay for flaky focus test

- package.json
- src/types.ts
- test/tsconfig.json
- test/type/mutator.ts
- yarn.lock
Resolve [issue#1769](https://github.com/vercel/swr/issues/1769#issue-1094864249)
> Required return type when mutating

- package.json
- test/use-swr-concurrent-rendering.test.tsx
- yarn.lock
This updates to the latest React/React DOM 18 release (`@next`).
> Update React 18 dependencies

- .eslintrc
- src/utils/state.ts
remove annoying lint warnings...
> lint: dont check unused vars with underscore prefix

- mutation/index.ts
- test/use-swr-remote-mutation.test.tsx
> fix: useSWRMutation - clear error after successful trigger (#1973)

- package.json
- pnpm-lock.yaml
https://github.com/facebook/react/pull/24289
> Upgrading use-sync-external-store lib

- _internal/utils/env.ts
- test/type/internal.tsx
- tsconfig.json
> Fix: raf return type

- tsconfig.json
Add the missing paths
https://github.com/vercel/swr/pull/2104#issuecomment-1206242665
> fix: add swr/_internal to paths

- .gitignore
- package.json
<details>
<summary>Before</summary>
```
npm notice 
npm notice 📦  swr@2.0.0-beta.6
npm notice === Tarball Contents === 
npm notice 119B   _internal/dist/_internal/constants.d.ts              
npm notice 1.1kB  _internal/dist/_internal/index.d.ts                  
npm notice 34.4kB _internal/dist/_internal/tsconfig.tsbuildinfo        
npm notice 11.5kB _internal/dist/_internal/types.d.ts                  
npm notice 299B   _internal/dist/_internal/utils/cache.d.ts            
npm notice 509B   _internal/dist/_internal/utils/config-context.d.ts   
npm notice 292B   _internal/dist/_internal/utils/config.d.ts           
npm notice 79B    _internal/dist/_internal/utils/devtools.d.ts         
npm notice 331B   _internal/dist/_internal/utils/env.d.ts              
npm notice 123B …
```
> chore: exclude .tsbuildinfo from files, reduce install size

- package.json
- pnpm-lock.yaml
Use higher version swc for deduping with the one from bunchee
> Dedupe installed swc

- _internal/package.json
- core/package.json
Accidently commit to last pr in #2150 ...
> Revert target option

- package.json
- pnpm-lock.yaml
Bump dep dev `bunchee` and `swc/core` to apply upstream bug fixes (especially swc)
> Bump bundler

- package.json
- pnpm-lock.yaml
> Fix missing esmodule mark in cjs build

- .codesandbox/ci.json
- _internal/types.ts
- infinite/types.ts
- package.json
- test/type/fetcher.ts
- test/type/option-fetcher.ts
* make typecheck more strict with `@type-challenges/utils`
* fix `SWRInfiniteHook` types
* simplify `SWRHook`
> Improve type test

- infinite/index.ts
- test/use-swr-infinite.test.tsx
fixes #1899
I have to add more tests for the options.
> feat: add all mutate options support to useSWRInfinite

- infinite/index.ts
- test/use-swr-infinite.test.tsx
Repro: https://codesandbox.io/s/2370-forked-nwkd2v
close #2370
> fix: when inifinite key changes, should use cached pagesize instead of initialSize

- core/use-swr.ts
> fix: make compare function only compare data (#2375)

- test/use-swr-refresh.test.tsx
> test: add test case for #2375

- README.md
It triggered my OCD that there were 2 types of `-`
> unify `-` characters in README.md

- .github/workflows/test-release.yml
x-ref: https://github.com/vercel/swr/actions/runs/4031850838/jobs/6931395895
> build: fix release job condition

- mutation/index.ts
- test/use-swr-remote-mutation.test.tsx
fixes #2462
This makes `useSWRMutation` use the latest config.
> fix: use the latest config in useSWRMutation

- examples/subscription/pages/index.js
This PR adds a basic example of using `useSWRSubscription` with an external data source.
> chore: Add subscription example

- package.json
> chore: remove engines

- subscription/index.ts
- test/use-swr-subscription.test.tsx
> Fix #2548: pass origin key to subcription callback

- .github/workflows/test-release.yml
- package.json
- pnpm-lock.yaml
bunchee v3 includes the feature of checking output asset with publint, we don't need to install it separately anymore
> Upgrade bundler

- .github/workflows/test-release.yml
close #2569 
https://docs.npmjs.com/generating-provenance-statements
> chore: use provenance for release

- package.json
- pnpm-lock.yaml
> fix: missing interop helpers in bundle

- .github/workflows/test-canary.yml
- package.json
- pnpm-lock.yaml
- test/use-swr-suspense.test.tsx
> ci: Add daily test job for react canary

- .github/workflows/test-release.yml
- .github/workflows/trigger-release.yml
determine the latest git tag and decide to publish it into corresponding npm channel
> build: determin release tag

- .github/workflows/trigger-release.yml
[slack-thread](https://vercel.slack.com/archives/C01LN7C5QR5/p1684849596794369?thread_ts=1684428058.764599&cid=C01LN7C5QR5)
> ci: update github token

- test/use-swr-suspense.test.tsx
> test: fix flaky suspense test in canary

- immutable/package.json
- infinite/package.json
- package.json
Fix for `next-site:build: Module not found: Can't resolve 'swr/immutable'`
> types: fix immutable export paths

- _internal/src/utils/state.ts
- e2e/test/mutate-server-action.test.ts
x-ref: https://github.com/vercel/swr/pull/2654#issuecomment-1599307815
> Revert "fix: remove startTransition so mutation hook could update immediately (#2654)"

- mutation/src/index.ts
- mutation/src/types.ts
> types: export mutation types

- test/type/mutate.ts
x-ref: https://github.com/vercel/swr/pull/2753/files#r1320768124
> test: update tests, use matched types for mutate api

- src/_internal/types.ts
- test/type/config.tsx
> types: isLoading typed as boolean when using fallbackData (#2866)

- scripts/bump-next-version.js
respect to semver type in beta release
> build: fix beta release job

- package.json
- pnpm-lock.yaml
- src/_internal/index.react-server.ts
- src/_internal/utils/config-context.ts
- src/index/config.ts
- src/index/index.react-server.ts
* Simplify the export and mark swr context with "use client"
* Upgrade bundler
> build: simplify react-server export and update bundler

- package.json
> chore: update pkg script watch

- package.json
- pnpm-lock.yaml
Bump bundler to get build performance from upstream
> build: bump bundler for perf

- e2e/site/app/suspense-after-preload/page.tsx
- e2e/site/app/suspense-retry-18-3/page.tsx
- e2e/site/next-env.d.ts
- package.json
- pnpm-lock.yaml
Upgrade next.js dev dep, and update the testing page to work in with next 15
> chore: upgrade nextjs dev dep for e2e testing

- .github/workflows/test-canary.yml
- .github/workflows/test-legacy-react.yml
- .github/workflows/test-release.yml
- test/tsconfig.json
Always do type checking job in `Test & Lint`
> fix type check in tests

- README.md
I'm so bored that updated the Twitter references to X.
> Update Twitter references to X
